# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_auto_pc_2/project_5_auto_pc_2.xci
# IP: The module: 'project_5_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_auto_pc_2/project_5_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_5_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_auto_pc_2/project_5_auto_pc_2.xci
# IP: The module: 'project_5_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_auto_pc_2/project_5_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_5_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
