-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Mat2AXIvideo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rows : IN STD_LOGIC_VECTOR (31 downto 0);
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    img_1_data_stream_0_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_1_data_stream_0_empty_n : IN STD_LOGIC;
    img_1_data_stream_0_read : OUT STD_LOGIC;
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of Mat2AXIvideo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv24_FFFFFF : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111111111111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal OUTPUT_STREAM_V_data_V_1_data_out : STD_LOGIC_VECTOR (31 downto 0);
    signal OUTPUT_STREAM_V_data_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_payload_A : STD_LOGIC_VECTOR (31 downto 0);
    signal OUTPUT_STREAM_V_data_V_1_payload_B : STD_LOGIC_VECTOR (31 downto 0);
    signal OUTPUT_STREAM_V_data_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_data_V_1_sel_wr : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_data_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_load_A : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_load_B : STD_LOGIC;
    signal OUTPUT_STREAM_V_data_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_data_V_1_state_cmp_full : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal OUTPUT_STREAM_V_keep_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_keep_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_keep_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_strb_V_1_data_out : STD_LOGIC_VECTOR (3 downto 0);
    signal OUTPUT_STREAM_V_strb_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_strb_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_strb_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_strb_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_strb_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_strb_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_strb_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_user_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_user_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_user_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_user_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_user_V_1_sel_wr : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_user_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_load_A : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_load_B : STD_LOGIC;
    signal OUTPUT_STREAM_V_user_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_user_V_1_state_cmp_full : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_last_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_payload_A : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_last_V_1_payload_B : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_last_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_last_V_1_sel_wr : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_last_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_load_A : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_load_B : STD_LOGIC;
    signal OUTPUT_STREAM_V_last_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_last_V_1_state_cmp_full : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_id_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_id_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_id_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal OUTPUT_STREAM_V_dest_V_1_data_out : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_V_dest_V_1_vld_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_dest_V_1_vld_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_dest_V_1_ack_in : STD_LOGIC;
    signal OUTPUT_STREAM_V_dest_V_1_ack_out : STD_LOGIC;
    signal OUTPUT_STREAM_V_dest_V_1_sel_rd : STD_LOGIC := '0';
    signal OUTPUT_STREAM_V_dest_V_1_sel : STD_LOGIC;
    signal OUTPUT_STREAM_V_dest_V_1_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal img_1_data_stream_0_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_flag00000000 : BOOLEAN;
    signal exitcond_i_i_reg_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal OUTPUT_STREAM_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_reg_pp0_iter1_exitcond_i_i_reg_268 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_1_i_i_reg_162 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_fu_173_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal tmp_1_fu_177_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal r_V_fu_181_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond1_i_i_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state2 : BOOLEAN;
    signal i_V_fu_197_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_V_reg_263 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond_i_i_fu_203_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011001 : BOOLEAN;
    signal j_V_fu_208_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal axi_last_V_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_reg_277 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_223_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_flag00011011 : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal p_i_i_reg_151 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_user_V_fu_100 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_flag00001001 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    OUTPUT_STREAM_V_data_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_data_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_data_V_1_sel_rd <= not(OUTPUT_STREAM_V_data_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_data_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_data_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_ack_in))) then 
                                        OUTPUT_STREAM_V_data_V_1_sel_wr <= not(OUTPUT_STREAM_V_data_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_data_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_data_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_ack_out) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_3)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_vld_in) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_2)))) then 
                    OUTPUT_STREAM_V_data_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_out) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_3)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_out) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_1)))) then 
                    OUTPUT_STREAM_V_data_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_vld_in) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_2)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_ack_out) and (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_1)) or ((OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_3) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_data_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_data_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_dest_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_dest_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_dest_V_1_sel_rd <= not(OUTPUT_STREAM_V_dest_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_dest_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_dest_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_dest_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_dest_V_1_state)))) then 
                    OUTPUT_STREAM_V_dest_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_dest_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_dest_V_1_state)))) then 
                    OUTPUT_STREAM_V_dest_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_dest_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_dest_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_dest_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_dest_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_dest_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_dest_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_id_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_id_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_id_V_1_sel_rd <= not(OUTPUT_STREAM_V_id_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_id_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_id_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_id_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_id_V_1_state)))) then 
                    OUTPUT_STREAM_V_id_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_id_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_id_V_1_state)))) then 
                    OUTPUT_STREAM_V_id_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_id_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_id_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_id_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_id_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_id_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_id_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_keep_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_keep_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_keep_V_1_sel_rd <= not(OUTPUT_STREAM_V_keep_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_keep_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_keep_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_keep_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_keep_V_1_state)))) then 
                    OUTPUT_STREAM_V_keep_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_keep_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_keep_V_1_state)))) then 
                    OUTPUT_STREAM_V_keep_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_keep_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_keep_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_keep_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_keep_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_keep_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_keep_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_last_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_last_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_last_V_1_sel_rd <= not(OUTPUT_STREAM_V_last_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_last_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_last_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_ack_in))) then 
                                        OUTPUT_STREAM_V_last_V_1_sel_wr <= not(OUTPUT_STREAM_V_last_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_last_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_last_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_last_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_last_V_1_state)))) then 
                    OUTPUT_STREAM_V_last_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_last_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_last_V_1_state)))) then 
                    OUTPUT_STREAM_V_last_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_last_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_last_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_last_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_last_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_last_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_strb_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_strb_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_strb_V_1_sel_rd <= not(OUTPUT_STREAM_V_strb_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_strb_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_strb_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_strb_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_strb_V_1_state)))) then 
                    OUTPUT_STREAM_V_strb_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_strb_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_strb_V_1_state)))) then 
                    OUTPUT_STREAM_V_strb_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_strb_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_strb_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_strb_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_strb_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_strb_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_strb_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_user_V_1_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_user_V_1_sel_rd <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_ack_out) and (ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_vld_out))) then 
                                        OUTPUT_STREAM_V_user_V_1_sel_rd <= not(OUTPUT_STREAM_V_user_V_1_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_user_V_1_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_user_V_1_sel_wr <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_ack_in))) then 
                                        OUTPUT_STREAM_V_user_V_1_sel_wr <= not(OUTPUT_STREAM_V_user_V_1_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    OUTPUT_STREAM_V_user_V_1_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                OUTPUT_STREAM_V_user_V_1_state <= ap_const_lv2_0;
            else
                if ((((ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_user_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_user_V_1_state)))) then 
                    OUTPUT_STREAM_V_user_V_1_state <= ap_const_lv2_2;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_out) and (ap_const_lv2_3 = OUTPUT_STREAM_V_user_V_1_state)) or ((ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_user_V_1_state)))) then 
                    OUTPUT_STREAM_V_user_V_1_state <= ap_const_lv2_1;
                elsif ((((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_lv2_2 = OUTPUT_STREAM_V_user_V_1_state)) or ((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_ack_out) and (ap_const_lv2_1 = OUTPUT_STREAM_V_user_V_1_state)) or ((ap_const_lv2_3 = OUTPUT_STREAM_V_user_V_1_state) and not(((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_out))) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_vld_in) and (ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_ack_out)))))) then 
                    OUTPUT_STREAM_V_user_V_1_state <= ap_const_lv2_3;
                else 
                    OUTPUT_STREAM_V_user_V_1_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_192_p2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_192_p2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state3 xor ap_const_logic_1);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_192_p2))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    p_1_i_i_reg_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_0 = exitcond_i_i_fu_203_p2))) then 
                p_1_i_i_reg_162 <= j_V_fu_208_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_192_p2))) then 
                p_1_i_i_reg_162 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    p_i_i_reg_151_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then 
                p_i_i_reg_151 <= ap_const_lv6_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                p_i_i_reg_151 <= i_V_reg_263;
            end if; 
        end if;
    end process;

    tmp_user_V_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
                tmp_user_V_fu_100 <= ap_const_lv1_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then 
                tmp_user_V_fu_100 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_load_A)) then
                OUTPUT_STREAM_V_data_V_1_payload_A <= p_Result_s_fu_223_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_load_B)) then
                OUTPUT_STREAM_V_data_V_1_payload_B <= p_Result_s_fu_223_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_load_A)) then
                OUTPUT_STREAM_V_last_V_1_payload_A <= axi_last_V_reg_277;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_load_B)) then
                OUTPUT_STREAM_V_last_V_1_payload_B <= axi_last_V_reg_277;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_load_A)) then
                OUTPUT_STREAM_V_user_V_1_payload_A <= tmp_user_V_fu_100;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_load_B)) then
                OUTPUT_STREAM_V_user_V_1_payload_B <= tmp_user_V_fu_100;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then
                ap_reg_pp0_iter1_exitcond_i_i_reg_268 <= exitcond_i_i_reg_268;
                exitcond_i_i_reg_268 <= exitcond_i_i_fu_203_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_i_i_fu_203_p2))) then
                axi_last_V_reg_277 <= axi_last_V_fu_214_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))))) then
                i_V_reg_263 <= i_V_fu_197_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, OUTPUT_STREAM_V_data_V_1_ack_in, OUTPUT_STREAM_V_keep_V_1_ack_in, OUTPUT_STREAM_V_strb_V_1_ack_in, OUTPUT_STREAM_V_user_V_1_ack_in, OUTPUT_STREAM_V_last_V_1_ack_in, OUTPUT_STREAM_V_id_V_1_ack_in, OUTPUT_STREAM_V_dest_V_1_ack_in, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, exitcond1_i_i_fu_192_p2, ap_CS_fsm_state2, exitcond_i_i_fu_203_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_flag00011011)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_192_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_0 = exitcond1_i_i_fu_192_p2))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_const_lv1_1 = exitcond_i_i_fu_203_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_const_lv1_1 = exitcond_i_i_fu_203_p2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    OUTPUT_STREAM_TDATA <= OUTPUT_STREAM_V_data_V_1_data_out;

    OUTPUT_STREAM_TDATA_blk_n_assign_proc : process(OUTPUT_STREAM_V_data_V_1_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000, exitcond_i_i_reg_268, ap_enable_reg_pp0_iter2, ap_reg_pp0_iter1_exitcond_i_i_reg_268)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_i_i_reg_268)) or ((ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_i_i_reg_268)))) then 
            OUTPUT_STREAM_TDATA_blk_n <= OUTPUT_STREAM_V_data_V_1_state(1);
        else 
            OUTPUT_STREAM_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    OUTPUT_STREAM_TDEST <= OUTPUT_STREAM_V_dest_V_1_data_out;
    OUTPUT_STREAM_TID <= OUTPUT_STREAM_V_id_V_1_data_out;
    OUTPUT_STREAM_TKEEP <= OUTPUT_STREAM_V_keep_V_1_data_out;
    OUTPUT_STREAM_TLAST <= OUTPUT_STREAM_V_last_V_1_data_out;
    OUTPUT_STREAM_TSTRB <= OUTPUT_STREAM_V_strb_V_1_data_out;
    OUTPUT_STREAM_TUSER <= OUTPUT_STREAM_V_user_V_1_data_out;
    OUTPUT_STREAM_TVALID <= OUTPUT_STREAM_V_dest_V_1_state(0);
    OUTPUT_STREAM_V_data_V_1_ack_in <= OUTPUT_STREAM_V_data_V_1_state(1);
    OUTPUT_STREAM_V_data_V_1_ack_out <= OUTPUT_STREAM_TREADY;

    OUTPUT_STREAM_V_data_V_1_data_out_assign_proc : process(OUTPUT_STREAM_V_data_V_1_payload_A, OUTPUT_STREAM_V_data_V_1_payload_B, OUTPUT_STREAM_V_data_V_1_sel)
    begin
        if ((ap_const_logic_1 = OUTPUT_STREAM_V_data_V_1_sel)) then 
            OUTPUT_STREAM_V_data_V_1_data_out <= OUTPUT_STREAM_V_data_V_1_payload_B;
        else 
            OUTPUT_STREAM_V_data_V_1_data_out <= OUTPUT_STREAM_V_data_V_1_payload_A;
        end if; 
    end process;

    OUTPUT_STREAM_V_data_V_1_load_A <= (OUTPUT_STREAM_V_data_V_1_state_cmp_full and not(OUTPUT_STREAM_V_data_V_1_sel_wr));
    OUTPUT_STREAM_V_data_V_1_load_B <= (OUTPUT_STREAM_V_data_V_1_sel_wr and OUTPUT_STREAM_V_data_V_1_state_cmp_full);
    OUTPUT_STREAM_V_data_V_1_sel <= OUTPUT_STREAM_V_data_V_1_sel_rd;
    OUTPUT_STREAM_V_data_V_1_state_cmp_full <= '0' when (OUTPUT_STREAM_V_data_V_1_state = ap_const_lv2_1) else '1';

    OUTPUT_STREAM_V_data_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_data_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_data_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_data_V_1_vld_out <= OUTPUT_STREAM_V_data_V_1_state(0);
    OUTPUT_STREAM_V_dest_V_1_ack_in <= OUTPUT_STREAM_V_dest_V_1_state(1);
    OUTPUT_STREAM_V_dest_V_1_ack_out <= OUTPUT_STREAM_TREADY;
    OUTPUT_STREAM_V_dest_V_1_data_out <= ap_const_lv1_0;
    OUTPUT_STREAM_V_dest_V_1_sel <= OUTPUT_STREAM_V_dest_V_1_sel_rd;

    OUTPUT_STREAM_V_dest_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_dest_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_dest_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_dest_V_1_vld_out <= OUTPUT_STREAM_V_dest_V_1_state(0);
    OUTPUT_STREAM_V_id_V_1_ack_in <= OUTPUT_STREAM_V_id_V_1_state(1);
    OUTPUT_STREAM_V_id_V_1_ack_out <= OUTPUT_STREAM_TREADY;
    OUTPUT_STREAM_V_id_V_1_data_out <= ap_const_lv1_0;
    OUTPUT_STREAM_V_id_V_1_sel <= OUTPUT_STREAM_V_id_V_1_sel_rd;

    OUTPUT_STREAM_V_id_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_id_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_id_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_id_V_1_vld_out <= OUTPUT_STREAM_V_id_V_1_state(0);
    OUTPUT_STREAM_V_keep_V_1_ack_in <= OUTPUT_STREAM_V_keep_V_1_state(1);
    OUTPUT_STREAM_V_keep_V_1_ack_out <= OUTPUT_STREAM_TREADY;
    OUTPUT_STREAM_V_keep_V_1_data_out <= ap_const_lv4_F;
    OUTPUT_STREAM_V_keep_V_1_sel <= OUTPUT_STREAM_V_keep_V_1_sel_rd;

    OUTPUT_STREAM_V_keep_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_keep_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_keep_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_keep_V_1_vld_out <= OUTPUT_STREAM_V_keep_V_1_state(0);
    OUTPUT_STREAM_V_last_V_1_ack_in <= OUTPUT_STREAM_V_last_V_1_state(1);
    OUTPUT_STREAM_V_last_V_1_ack_out <= OUTPUT_STREAM_TREADY;

    OUTPUT_STREAM_V_last_V_1_data_out_assign_proc : process(OUTPUT_STREAM_V_last_V_1_payload_A, OUTPUT_STREAM_V_last_V_1_payload_B, OUTPUT_STREAM_V_last_V_1_sel)
    begin
        if ((ap_const_logic_1 = OUTPUT_STREAM_V_last_V_1_sel)) then 
            OUTPUT_STREAM_V_last_V_1_data_out <= OUTPUT_STREAM_V_last_V_1_payload_B;
        else 
            OUTPUT_STREAM_V_last_V_1_data_out <= OUTPUT_STREAM_V_last_V_1_payload_A;
        end if; 
    end process;

    OUTPUT_STREAM_V_last_V_1_load_A <= (OUTPUT_STREAM_V_last_V_1_state_cmp_full and not(OUTPUT_STREAM_V_last_V_1_sel_wr));
    OUTPUT_STREAM_V_last_V_1_load_B <= (OUTPUT_STREAM_V_last_V_1_sel_wr and OUTPUT_STREAM_V_last_V_1_state_cmp_full);
    OUTPUT_STREAM_V_last_V_1_sel <= OUTPUT_STREAM_V_last_V_1_sel_rd;
    OUTPUT_STREAM_V_last_V_1_state_cmp_full <= '0' when (OUTPUT_STREAM_V_last_V_1_state = ap_const_lv2_1) else '1';

    OUTPUT_STREAM_V_last_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_last_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_last_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_last_V_1_vld_out <= OUTPUT_STREAM_V_last_V_1_state(0);
    OUTPUT_STREAM_V_strb_V_1_ack_in <= OUTPUT_STREAM_V_strb_V_1_state(1);
    OUTPUT_STREAM_V_strb_V_1_ack_out <= OUTPUT_STREAM_TREADY;
    OUTPUT_STREAM_V_strb_V_1_data_out <= ap_const_lv4_0;
    OUTPUT_STREAM_V_strb_V_1_sel <= OUTPUT_STREAM_V_strb_V_1_sel_rd;

    OUTPUT_STREAM_V_strb_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_strb_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_strb_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_strb_V_1_vld_out <= OUTPUT_STREAM_V_strb_V_1_state(0);
    OUTPUT_STREAM_V_user_V_1_ack_in <= OUTPUT_STREAM_V_user_V_1_state(1);
    OUTPUT_STREAM_V_user_V_1_ack_out <= OUTPUT_STREAM_TREADY;

    OUTPUT_STREAM_V_user_V_1_data_out_assign_proc : process(OUTPUT_STREAM_V_user_V_1_payload_A, OUTPUT_STREAM_V_user_V_1_payload_B, OUTPUT_STREAM_V_user_V_1_sel)
    begin
        if ((ap_const_logic_1 = OUTPUT_STREAM_V_user_V_1_sel)) then 
            OUTPUT_STREAM_V_user_V_1_data_out <= OUTPUT_STREAM_V_user_V_1_payload_B;
        else 
            OUTPUT_STREAM_V_user_V_1_data_out <= OUTPUT_STREAM_V_user_V_1_payload_A;
        end if; 
    end process;

    OUTPUT_STREAM_V_user_V_1_load_A <= (OUTPUT_STREAM_V_user_V_1_state_cmp_full and not(OUTPUT_STREAM_V_user_V_1_sel_wr));
    OUTPUT_STREAM_V_user_V_1_load_B <= (OUTPUT_STREAM_V_user_V_1_sel_wr and OUTPUT_STREAM_V_user_V_1_state_cmp_full);
    OUTPUT_STREAM_V_user_V_1_sel <= OUTPUT_STREAM_V_user_V_1_sel_rd;
    OUTPUT_STREAM_V_user_V_1_state_cmp_full <= '0' when (OUTPUT_STREAM_V_user_V_1_state = ap_const_lv2_1) else '1';

    OUTPUT_STREAM_V_user_V_1_vld_in_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            OUTPUT_STREAM_V_user_V_1_vld_in <= ap_const_logic_1;
        else 
            OUTPUT_STREAM_V_user_V_1_vld_in <= ap_const_logic_0;
        end if; 
    end process;

    OUTPUT_STREAM_V_user_V_1_vld_out <= OUTPUT_STREAM_V_user_V_1_state(0);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_flag00001001_assign_proc : process(img_1_data_stream_0_empty_n, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268)
    begin
                ap_block_pp0_stage0_flag00001001 <= ((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_const_logic_0 = img_1_data_stream_0_empty_n));
    end process;


    ap_block_pp0_stage0_flag00011001_assign_proc : process(img_1_data_stream_0_empty_n, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_enable_reg_pp0_iter2, ap_block_state4_io, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_flag00011001 <= (((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_const_logic_0 = img_1_data_stream_0_empty_n)) or (ap_const_boolean_1 = ap_block_state4_io))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_const_boolean_1 = ap_block_state5_io)));
    end process;


    ap_block_pp0_stage0_flag00011011_assign_proc : process(img_1_data_stream_0_empty_n, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_enable_reg_pp0_iter2, ap_block_state4_io, ap_block_state5_io)
    begin
                ap_block_pp0_stage0_flag00011011 <= (((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (((ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_const_logic_0 = img_1_data_stream_0_empty_n)) or (ap_const_boolean_1 = ap_block_state4_io))) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter2) and (ap_const_boolean_1 = ap_block_state5_io)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(OUTPUT_STREAM_V_data_V_1_ack_in, OUTPUT_STREAM_V_keep_V_1_ack_in, OUTPUT_STREAM_V_strb_V_1_ack_in, OUTPUT_STREAM_V_user_V_1_ack_in, OUTPUT_STREAM_V_last_V_1_ack_in, OUTPUT_STREAM_V_id_V_1_ack_in, OUTPUT_STREAM_V_dest_V_1_ack_in)
    begin
                ap_block_state2 <= ((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_io_assign_proc : process(OUTPUT_STREAM_V_data_V_1_ack_in, exitcond_i_i_reg_268)
    begin
                ap_block_state4_io <= ((ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(img_1_data_stream_0_empty_n, exitcond_i_i_reg_268)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_const_logic_0 = img_1_data_stream_0_empty_n));
    end process;


    ap_block_state5_io_assign_proc : process(OUTPUT_STREAM_V_data_V_1_ack_in, ap_reg_pp0_iter1_exitcond_i_i_reg_268)
    begin
                ap_block_state5_io <= ((ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_i_i_reg_268) and (ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in));
    end process;

        ap_block_state5_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(exitcond_i_i_fu_203_p2)
    begin
        if ((ap_const_lv1_1 = exitcond_i_i_fu_203_p2)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, OUTPUT_STREAM_V_data_V_1_ack_in, OUTPUT_STREAM_V_keep_V_1_ack_in, OUTPUT_STREAM_V_strb_V_1_ack_in, OUTPUT_STREAM_V_user_V_1_ack_in, OUTPUT_STREAM_V_last_V_1_ack_in, OUTPUT_STREAM_V_id_V_1_ack_in, OUTPUT_STREAM_V_dest_V_1_ack_in, exitcond1_i_i_fu_192_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_192_p2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(OUTPUT_STREAM_V_data_V_1_ack_in, OUTPUT_STREAM_V_keep_V_1_ack_in, OUTPUT_STREAM_V_strb_V_1_ack_in, OUTPUT_STREAM_V_user_V_1_ack_in, OUTPUT_STREAM_V_last_V_1_ack_in, OUTPUT_STREAM_V_id_V_1_ack_in, OUTPUT_STREAM_V_dest_V_1_ack_in, exitcond1_i_i_fu_192_p2, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and not(((ap_const_logic_0 = OUTPUT_STREAM_V_data_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_keep_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_strb_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_user_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_last_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_id_V_1_ack_in) or (ap_const_logic_0 = OUTPUT_STREAM_V_dest_V_1_ack_in))) and (ap_const_lv1_1 = exitcond1_i_i_fu_192_p2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axi_last_V_fu_214_p2 <= "1" when (p_1_i_i_reg_162 = r_V_fu_181_p2) else "0";
    exitcond1_i_i_fu_192_p2 <= "1" when (p_i_i_reg_151 = tmp_fu_173_p1) else "0";
    exitcond_i_i_fu_203_p2 <= "1" when (p_1_i_i_reg_162 = tmp_1_fu_177_p1) else "0";
    i_V_fu_197_p2 <= std_logic_vector(unsigned(p_i_i_reg_151) + unsigned(ap_const_lv6_1));

    img_1_data_stream_0_blk_n_assign_proc : process(img_1_data_stream_0_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000, exitcond_i_i_reg_268)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0) and (ap_const_lv1_0 = exitcond_i_i_reg_268))) then 
            img_1_data_stream_0_blk_n <= img_1_data_stream_0_empty_n;
        else 
            img_1_data_stream_0_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_1_data_stream_0_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_i_i_reg_268, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_const_lv1_0 = exitcond_i_i_reg_268) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            img_1_data_stream_0_read <= ap_const_logic_1;
        else 
            img_1_data_stream_0_read <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_208_p2 <= std_logic_vector(unsigned(p_1_i_i_reg_162) + unsigned(ap_const_lv6_1));
    p_Result_s_fu_223_p3 <= (ap_const_lv24_FFFFFF & img_1_data_stream_0_dout);
    r_V_fu_181_p2 <= std_logic_vector(unsigned(tmp_1_fu_177_p1) + unsigned(ap_const_lv6_3F));
    tmp_1_fu_177_p1 <= cols(6 - 1 downto 0);
    tmp_fu_173_p1 <= rows(6 - 1 downto 0);
end behav;
