# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/project_5_axi_smc_0.xci
# IP: The module: 'project_5_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/bd_7baa.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_42/bd_7baa_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_51/bd_7baa_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_57/bd_7baa_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_63/bd_7baa_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_58/bd_7baa_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_59/bd_7baa_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_60/bd_7baa_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_61/bd_7baa_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_62/bd_7baa_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_52/bd_7baa_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_53/bd_7baa_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_54/bd_7baa_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_55/bd_7baa_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_56/bd_7baa_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_48/bd_7baa_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_49/bd_7baa_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_50/bd_7baa_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_43/bd_7baa_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_44/bd_7baa_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_45/bd_7baa_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_46/bd_7baa_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_47/bd_7baa_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_39/bd_7baa_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_40/bd_7baa_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_41/bd_7baa_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_34/bd_7baa_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_35/bd_7baa_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_36/bd_7baa_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_37/bd_7baa_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_38/bd_7baa_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_32/bd_7baa_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_42/bd_7baa_s00a2s_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_51/bd_7baa_s01a2s_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_57/bd_7baa_m00s2a_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_58/bd_7baa_m00arn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_59/bd_7baa_m00rn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_60/bd_7baa_m00awn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_61/bd_7baa_m00wn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_62/bd_7baa_m00bn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_52/bd_7baa_sarn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_53/bd_7baa_srn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_54/bd_7baa_sawn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_55/bd_7baa_swn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_56/bd_7baa_sbn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_43/bd_7baa_sarn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_44/bd_7baa_srn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_45/bd_7baa_sawn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_46/bd_7baa_swn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_47/bd_7baa_sbn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_34/bd_7baa_arsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_35/bd_7baa_rsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_36/bd_7baa_awsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_37/bd_7baa_wsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_38/bd_7baa_bsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_5_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/project_5_axi_smc_0.xci
# IP: The module: 'project_5_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/bd_7baa.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_42/bd_7baa_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_51/bd_7baa_s01a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_57/bd_7baa_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_63/bd_7baa_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_58/bd_7baa_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_59/bd_7baa_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_60/bd_7baa_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_61/bd_7baa_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_62/bd_7baa_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_52/bd_7baa_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_53/bd_7baa_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_54/bd_7baa_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_55/bd_7baa_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_56/bd_7baa_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_48/bd_7baa_s01mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_49/bd_7baa_s01tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_50/bd_7baa_s01sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_43/bd_7baa_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_44/bd_7baa_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_45/bd_7baa_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_46/bd_7baa_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_47/bd_7baa_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_39/bd_7baa_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_40/bd_7baa_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_41/bd_7baa_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_34/bd_7baa_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_35/bd_7baa_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_36/bd_7baa_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_37/bd_7baa_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_38/bd_7baa_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_32/bd_7baa_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_42/bd_7baa_s00a2s_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_51/bd_7baa_s01a2s_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_57/bd_7baa_m00s2a_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_58/bd_7baa_m00arn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_59/bd_7baa_m00rn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_60/bd_7baa_m00awn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_61/bd_7baa_m00wn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_62/bd_7baa_m00bn_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_52/bd_7baa_sarn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_53/bd_7baa_srn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_54/bd_7baa_sawn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_55/bd_7baa_swn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_56/bd_7baa_sbn_3_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_43/bd_7baa_sarn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_44/bd_7baa_srn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_45/bd_7baa_sawn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_46/bd_7baa_swn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_47/bd_7baa_sbn_2_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_34/bd_7baa_arsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_35/bd_7baa_rsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_36/bd_7baa_awsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_37/bd_7baa_wsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_38/bd_7baa_bsw_1_ooc.xdc

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/bd_0/ip/ip_33/bd_7baa_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trakaros/tou_nikou/lab5_hw_hls/lab5_hw_hls.srcs/sources_1/bd/project_5/ip/project_5_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'project_5_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
