// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ip_sobel,hls_ip_2017_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=20021,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=1651,HLS_SYN_LUT=2410}" *)

module ip_sobel (
        ap_clk,
        ap_rst_n,
        m_axi_input_img_AWVALID,
        m_axi_input_img_AWREADY,
        m_axi_input_img_AWADDR,
        m_axi_input_img_AWID,
        m_axi_input_img_AWLEN,
        m_axi_input_img_AWSIZE,
        m_axi_input_img_AWBURST,
        m_axi_input_img_AWLOCK,
        m_axi_input_img_AWCACHE,
        m_axi_input_img_AWPROT,
        m_axi_input_img_AWQOS,
        m_axi_input_img_AWREGION,
        m_axi_input_img_AWUSER,
        m_axi_input_img_WVALID,
        m_axi_input_img_WREADY,
        m_axi_input_img_WDATA,
        m_axi_input_img_WSTRB,
        m_axi_input_img_WLAST,
        m_axi_input_img_WID,
        m_axi_input_img_WUSER,
        m_axi_input_img_ARVALID,
        m_axi_input_img_ARREADY,
        m_axi_input_img_ARADDR,
        m_axi_input_img_ARID,
        m_axi_input_img_ARLEN,
        m_axi_input_img_ARSIZE,
        m_axi_input_img_ARBURST,
        m_axi_input_img_ARLOCK,
        m_axi_input_img_ARCACHE,
        m_axi_input_img_ARPROT,
        m_axi_input_img_ARQOS,
        m_axi_input_img_ARREGION,
        m_axi_input_img_ARUSER,
        m_axi_input_img_RVALID,
        m_axi_input_img_RREADY,
        m_axi_input_img_RDATA,
        m_axi_input_img_RLAST,
        m_axi_input_img_RID,
        m_axi_input_img_RUSER,
        m_axi_input_img_RRESP,
        m_axi_input_img_BVALID,
        m_axi_input_img_BREADY,
        m_axi_input_img_BRESP,
        m_axi_input_img_BID,
        m_axi_input_img_BUSER,
        m_axi_output_img_AWVALID,
        m_axi_output_img_AWREADY,
        m_axi_output_img_AWADDR,
        m_axi_output_img_AWID,
        m_axi_output_img_AWLEN,
        m_axi_output_img_AWSIZE,
        m_axi_output_img_AWBURST,
        m_axi_output_img_AWLOCK,
        m_axi_output_img_AWCACHE,
        m_axi_output_img_AWPROT,
        m_axi_output_img_AWQOS,
        m_axi_output_img_AWREGION,
        m_axi_output_img_AWUSER,
        m_axi_output_img_WVALID,
        m_axi_output_img_WREADY,
        m_axi_output_img_WDATA,
        m_axi_output_img_WSTRB,
        m_axi_output_img_WLAST,
        m_axi_output_img_WID,
        m_axi_output_img_WUSER,
        m_axi_output_img_ARVALID,
        m_axi_output_img_ARREADY,
        m_axi_output_img_ARADDR,
        m_axi_output_img_ARID,
        m_axi_output_img_ARLEN,
        m_axi_output_img_ARSIZE,
        m_axi_output_img_ARBURST,
        m_axi_output_img_ARLOCK,
        m_axi_output_img_ARCACHE,
        m_axi_output_img_ARPROT,
        m_axi_output_img_ARQOS,
        m_axi_output_img_ARREGION,
        m_axi_output_img_ARUSER,
        m_axi_output_img_RVALID,
        m_axi_output_img_RREADY,
        m_axi_output_img_RDATA,
        m_axi_output_img_RLAST,
        m_axi_output_img_RID,
        m_axi_output_img_RUSER,
        m_axi_output_img_RRESP,
        m_axi_output_img_BVALID,
        m_axi_output_img_BREADY,
        m_axi_output_img_BRESP,
        m_axi_output_img_BID,
        m_axi_output_img_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_pp0_stage0 = 10'd2;
parameter    ap_ST_fsm_pp0_stage1 = 10'd4;
parameter    ap_ST_fsm_pp0_stage2 = 10'd8;
parameter    ap_ST_fsm_pp0_stage3 = 10'd16;
parameter    ap_ST_fsm_pp0_stage4 = 10'd32;
parameter    ap_ST_fsm_pp0_stage5 = 10'd64;
parameter    ap_ST_fsm_pp0_stage6 = 10'd128;
parameter    ap_ST_fsm_pp0_stage7 = 10'd256;
parameter    ap_ST_fsm_state30 = 10'd512;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_INPUT_IMG_ID_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_ADDR_WIDTH = 32;
parameter    C_M_AXI_INPUT_IMG_DATA_WIDTH = 32;
parameter    C_M_AXI_INPUT_IMG_AWUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_ARUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_WUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_RUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_BUSER_WIDTH = 1;
parameter    C_M_AXI_INPUT_IMG_TARGET_ADDR = 0;
parameter    C_M_AXI_INPUT_IMG_USER_VALUE = 0;
parameter    C_M_AXI_INPUT_IMG_PROT_VALUE = 0;
parameter    C_M_AXI_INPUT_IMG_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_IMG_ID_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_ADDR_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_IMG_DATA_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_IMG_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_IMG_TARGET_ADDR = 0;
parameter    C_M_AXI_OUTPUT_IMG_USER_VALUE = 0;
parameter    C_M_AXI_OUTPUT_IMG_PROT_VALUE = 0;
parameter    C_M_AXI_OUTPUT_IMG_CACHE_VALUE = 3;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_INPUT_IMG_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUTPUT_IMG_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_input_img_AWVALID;
input   m_axi_input_img_AWREADY;
output  [C_M_AXI_INPUT_IMG_ADDR_WIDTH - 1:0] m_axi_input_img_AWADDR;
output  [C_M_AXI_INPUT_IMG_ID_WIDTH - 1:0] m_axi_input_img_AWID;
output  [7:0] m_axi_input_img_AWLEN;
output  [2:0] m_axi_input_img_AWSIZE;
output  [1:0] m_axi_input_img_AWBURST;
output  [1:0] m_axi_input_img_AWLOCK;
output  [3:0] m_axi_input_img_AWCACHE;
output  [2:0] m_axi_input_img_AWPROT;
output  [3:0] m_axi_input_img_AWQOS;
output  [3:0] m_axi_input_img_AWREGION;
output  [C_M_AXI_INPUT_IMG_AWUSER_WIDTH - 1:0] m_axi_input_img_AWUSER;
output   m_axi_input_img_WVALID;
input   m_axi_input_img_WREADY;
output  [C_M_AXI_INPUT_IMG_DATA_WIDTH - 1:0] m_axi_input_img_WDATA;
output  [C_M_AXI_INPUT_IMG_WSTRB_WIDTH - 1:0] m_axi_input_img_WSTRB;
output   m_axi_input_img_WLAST;
output  [C_M_AXI_INPUT_IMG_ID_WIDTH - 1:0] m_axi_input_img_WID;
output  [C_M_AXI_INPUT_IMG_WUSER_WIDTH - 1:0] m_axi_input_img_WUSER;
output   m_axi_input_img_ARVALID;
input   m_axi_input_img_ARREADY;
output  [C_M_AXI_INPUT_IMG_ADDR_WIDTH - 1:0] m_axi_input_img_ARADDR;
output  [C_M_AXI_INPUT_IMG_ID_WIDTH - 1:0] m_axi_input_img_ARID;
output  [7:0] m_axi_input_img_ARLEN;
output  [2:0] m_axi_input_img_ARSIZE;
output  [1:0] m_axi_input_img_ARBURST;
output  [1:0] m_axi_input_img_ARLOCK;
output  [3:0] m_axi_input_img_ARCACHE;
output  [2:0] m_axi_input_img_ARPROT;
output  [3:0] m_axi_input_img_ARQOS;
output  [3:0] m_axi_input_img_ARREGION;
output  [C_M_AXI_INPUT_IMG_ARUSER_WIDTH - 1:0] m_axi_input_img_ARUSER;
input   m_axi_input_img_RVALID;
output   m_axi_input_img_RREADY;
input  [C_M_AXI_INPUT_IMG_DATA_WIDTH - 1:0] m_axi_input_img_RDATA;
input   m_axi_input_img_RLAST;
input  [C_M_AXI_INPUT_IMG_ID_WIDTH - 1:0] m_axi_input_img_RID;
input  [C_M_AXI_INPUT_IMG_RUSER_WIDTH - 1:0] m_axi_input_img_RUSER;
input  [1:0] m_axi_input_img_RRESP;
input   m_axi_input_img_BVALID;
output   m_axi_input_img_BREADY;
input  [1:0] m_axi_input_img_BRESP;
input  [C_M_AXI_INPUT_IMG_ID_WIDTH - 1:0] m_axi_input_img_BID;
input  [C_M_AXI_INPUT_IMG_BUSER_WIDTH - 1:0] m_axi_input_img_BUSER;
output   m_axi_output_img_AWVALID;
input   m_axi_output_img_AWREADY;
output  [C_M_AXI_OUTPUT_IMG_ADDR_WIDTH - 1:0] m_axi_output_img_AWADDR;
output  [C_M_AXI_OUTPUT_IMG_ID_WIDTH - 1:0] m_axi_output_img_AWID;
output  [7:0] m_axi_output_img_AWLEN;
output  [2:0] m_axi_output_img_AWSIZE;
output  [1:0] m_axi_output_img_AWBURST;
output  [1:0] m_axi_output_img_AWLOCK;
output  [3:0] m_axi_output_img_AWCACHE;
output  [2:0] m_axi_output_img_AWPROT;
output  [3:0] m_axi_output_img_AWQOS;
output  [3:0] m_axi_output_img_AWREGION;
output  [C_M_AXI_OUTPUT_IMG_AWUSER_WIDTH - 1:0] m_axi_output_img_AWUSER;
output   m_axi_output_img_WVALID;
input   m_axi_output_img_WREADY;
output  [C_M_AXI_OUTPUT_IMG_DATA_WIDTH - 1:0] m_axi_output_img_WDATA;
output  [C_M_AXI_OUTPUT_IMG_WSTRB_WIDTH - 1:0] m_axi_output_img_WSTRB;
output   m_axi_output_img_WLAST;
output  [C_M_AXI_OUTPUT_IMG_ID_WIDTH - 1:0] m_axi_output_img_WID;
output  [C_M_AXI_OUTPUT_IMG_WUSER_WIDTH - 1:0] m_axi_output_img_WUSER;
output   m_axi_output_img_ARVALID;
input   m_axi_output_img_ARREADY;
output  [C_M_AXI_OUTPUT_IMG_ADDR_WIDTH - 1:0] m_axi_output_img_ARADDR;
output  [C_M_AXI_OUTPUT_IMG_ID_WIDTH - 1:0] m_axi_output_img_ARID;
output  [7:0] m_axi_output_img_ARLEN;
output  [2:0] m_axi_output_img_ARSIZE;
output  [1:0] m_axi_output_img_ARBURST;
output  [1:0] m_axi_output_img_ARLOCK;
output  [3:0] m_axi_output_img_ARCACHE;
output  [2:0] m_axi_output_img_ARPROT;
output  [3:0] m_axi_output_img_ARQOS;
output  [3:0] m_axi_output_img_ARREGION;
output  [C_M_AXI_OUTPUT_IMG_ARUSER_WIDTH - 1:0] m_axi_output_img_ARUSER;
input   m_axi_output_img_RVALID;
output   m_axi_output_img_RREADY;
input  [C_M_AXI_OUTPUT_IMG_DATA_WIDTH - 1:0] m_axi_output_img_RDATA;
input   m_axi_output_img_RLAST;
input  [C_M_AXI_OUTPUT_IMG_ID_WIDTH - 1:0] m_axi_output_img_RID;
input  [C_M_AXI_OUTPUT_IMG_RUSER_WIDTH - 1:0] m_axi_output_img_RUSER;
input  [1:0] m_axi_output_img_RRESP;
input   m_axi_output_img_BVALID;
output   m_axi_output_img_BREADY;
input  [1:0] m_axi_output_img_BRESP;
input  [C_M_AXI_OUTPUT_IMG_ID_WIDTH - 1:0] m_axi_output_img_BID;
input  [C_M_AXI_OUTPUT_IMG_BUSER_WIDTH - 1:0] m_axi_output_img_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg    input_img_blk_n_AR;
wire    ap_CS_fsm_pp0_stage5;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage5_flag00000000;
reg   [0:0] exitcond_flatten_reg_613;
reg   [0:0] or_cond5_reg_657;
reg    input_img_blk_n_R;
wire    ap_CS_fsm_pp0_stage4;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage4_flag00000000;
reg   [0:0] ap_reg_pp0_iter1_or_cond5_reg_657;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_flag00000000;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_flag00000000;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_flag00000000;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_flag00000000;
reg    ap_enable_reg_pp0_iter2;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_flag00000000;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_flag00000000;
reg   [0:0] ap_reg_pp0_iter2_or_cond5_reg_657;
reg    output_img_blk_n_AW;
reg    output_img_blk_n_W;
reg    output_img_blk_n_B;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] ap_reg_pp0_iter3_or_cond5_reg_657;
wire    input_img_AWREADY;
wire    input_img_WREADY;
reg    input_img_ARVALID;
wire    input_img_ARREADY;
reg   [31:0] input_img_ARADDR;
wire    input_img_RVALID;
reg    input_img_RREADY;
wire   [7:0] input_img_RDATA;
wire    input_img_RLAST;
wire   [0:0] input_img_RID;
wire   [0:0] input_img_RUSER;
wire   [1:0] input_img_RRESP;
wire    input_img_BVALID;
wire   [1:0] input_img_BRESP;
wire   [0:0] input_img_BID;
wire   [0:0] input_img_BUSER;
reg    output_img_AWVALID;
wire    output_img_AWREADY;
reg    output_img_WVALID;
wire    output_img_WREADY;
wire    output_img_ARREADY;
wire    output_img_RVALID;
wire   [7:0] output_img_RDATA;
wire    output_img_RLAST;
wire   [0:0] output_img_RID;
wire   [0:0] output_img_RUSER;
wire   [1:0] output_img_RRESP;
wire    output_img_BVALID;
reg    output_img_BREADY;
wire   [1:0] output_img_BRESP;
wire   [0:0] output_img_BID;
wire   [0:0] output_img_BUSER;
reg   [11:0] indvar_flatten_reg_109;
reg   [5:0] i_reg_120;
reg   [5:0] j_reg_131;
reg   [7:0] reg_142;
wire    ap_block_state6_pp0_stage4_iter0;
reg    ap_block_state14_pp0_stage4_iter1;
reg    ap_sig_ioackin_input_img_ARREADY;
reg    ap_block_state14_io;
wire    ap_block_state22_pp0_stage4_iter2;
reg    ap_block_pp0_stage4_flag00011001;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state12_pp0_stage2_iter1;
reg    ap_block_state12_io;
reg    ap_block_state20_pp0_stage2_iter2;
wire    ap_block_state28_pp0_stage2_iter3;
reg    ap_block_pp0_stage2_flag00011001;
reg   [7:0] reg_146;
wire    ap_block_state7_pp0_stage5_iter0;
reg    ap_predicate_op77_readreq_state7;
reg    ap_block_state7_io;
reg    ap_block_state15_pp0_stage5_iter1;
wire    ap_block_state23_pp0_stage5_iter2;
reg    ap_sig_ioackin_output_img_AWREADY;
reg    ap_block_state23_io;
reg    ap_block_pp0_stage5_flag00011001;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state13_pp0_stage3_iter1;
reg    ap_block_state13_io;
reg    ap_block_state21_pp0_stage3_iter2;
reg    ap_block_state29_pp0_stage3_iter3;
reg    ap_block_pp0_stage3_flag00011001;
wire   [0:0] tmp1_fu_162_p2;
reg   [0:0] tmp1_reg_608;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state10_pp0_stage0_iter1;
reg    ap_block_state10_io;
reg    ap_block_state18_pp0_stage0_iter2;
wire    ap_block_state26_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_flag00011001;
wire   [0:0] exitcond_flatten_fu_168_p2;
wire   [11:0] indvar_flatten_next_fu_174_p2;
reg   [11:0] indvar_flatten_next_reg_617;
wire   [0:0] exitcond_fu_180_p2;
reg   [0:0] exitcond_reg_622;
wire   [5:0] j_mid2_fu_186_p3;
reg   [5:0] j_mid2_reg_627;
wire   [0:0] tmp_mid1_fu_200_p2;
reg   [0:0] tmp_mid1_reg_636;
wire   [0:0] tmp_1_mid1_fu_206_p2;
reg   [0:0] tmp_1_mid1_reg_641;
wire   [5:0] tmp_2_mid2_v_v_fu_212_p3;
reg   [5:0] tmp_2_mid2_v_v_reg_646;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state11_pp0_stage1_iter1;
reg    ap_block_state11_io;
reg    ap_block_state19_pp0_stage1_iter2;
wire    ap_block_state27_pp0_stage1_iter3;
reg    ap_block_pp0_stage1_flag00011001;
wire   [0:0] or_cond5_fu_255_p2;
wire   [11:0] grp_fu_223_p2;
reg   [11:0] tmp_2_mid2_reg_661;
wire   [11:0] tmp_s_fu_277_p2;
reg   [11:0] tmp_s_reg_668;
reg   [31:0] input_img_addr_reg_674;
wire   [11:0] tmp_10_1_fu_298_p2;
reg   [11:0] tmp_10_1_reg_680;
wire   [11:0] tmp_10_2_fu_313_p2;
reg   [11:0] tmp_10_2_reg_687;
wire   [5:0] j_1_fu_318_p2;
reg   [5:0] j_1_reg_694;
wire    ap_block_state8_pp0_stage6_iter0;
reg    ap_predicate_op81_readreq_state8;
reg    ap_block_state8_io;
reg    ap_block_state16_pp0_stage6_iter1;
wire    ap_block_state24_pp0_stage6_iter2;
reg    ap_sig_ioackin_output_img_WREADY;
reg    ap_block_state24_io;
reg    ap_block_pp0_stage6_flag00011001;
reg   [31:0] input_img_addr_2_reg_705;
reg   [31:0] input_img_addr_3_reg_711;
wire    ap_block_state9_pp0_stage7_iter0;
reg    ap_predicate_op87_readreq_state9;
reg    ap_block_state9_io;
reg    ap_block_state17_pp0_stage7_iter1;
wire    ap_block_state25_pp0_stage7_iter2;
reg    ap_block_pp0_stage7_flag00011001;
reg   [31:0] input_img_addr_4_reg_717;
reg   [31:0] output_img_addr_reg_723;
reg   [31:0] ap_reg_pp0_iter2_output_img_addr_reg_723;
reg   [31:0] input_img_addr_5_reg_728;
reg   [31:0] input_img_addr_7_reg_740;
reg   [7:0] input_img_addr_2_rea_reg_746;
reg   [7:0] input_img_addr_3_rea_reg_751;
reg   [7:0] input_img_addr_4_rea_reg_756;
reg   [7:0] input_img_addr_5_rea_reg_761;
wire   [8:0] x_dir_2_0_2_fu_434_p2;
reg   [8:0] x_dir_2_0_2_reg_766;
wire   [8:0] tmp4_fu_440_p2;
reg   [8:0] tmp4_reg_771;
wire   [10:0] x_dir_2_2_fu_511_p2;
reg   [10:0] x_dir_2_2_reg_776;
wire   [10:0] y_dir_2_2_fu_517_p2;
reg   [10:0] y_dir_2_2_reg_781;
wire   [7:0] tmp_8_fu_523_p1;
reg   [7:0] tmp_8_reg_786;
wire   [7:0] tmp_9_fu_559_p2;
reg   [7:0] tmp_9_reg_791;
wire   [0:0] abscond_fu_564_p2;
reg   [0:0] abscond_reg_797;
wire   [7:0] tmp_12_fu_570_p1;
reg   [7:0] tmp_12_reg_802;
wire   [0:0] abscond7_fu_574_p2;
reg   [0:0] abscond7_reg_808;
wire   [7:0] tmp_6_fu_602_p2;
reg   [7:0] tmp_6_reg_813;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp0_stage7_flag00011011;
reg    ap_block_pp0_stage3_flag00011011;
reg   [11:0] indvar_flatten_phi_fu_113_p4;
reg   [5:0] i_phi_fu_124_p4;
reg   [5:0] j_phi_fu_135_p4;
wire   [63:0] tmp_3_fu_288_p1;
wire   [63:0] tmp_12_0_1_fu_323_p1;
wire   [63:0] tmp_12_0_2_fu_338_p1;
wire   [63:0] tmp_12_1_fu_353_p1;
wire   [63:0] tmp_12_1_2_fu_371_p1;
wire   [63:0] tmp_12_1_1_fu_363_p1;
wire   [63:0] tmp_12_2_fu_392_p1;
wire   [63:0] tmp_12_2_1_fu_402_p1;
wire   [63:0] tmp_12_2_2_fu_417_p1;
reg    ap_reg_ioackin_input_img_ARREADY;
reg    ap_block_pp0_stage5_flag00001001;
reg    ap_block_pp0_stage6_flag00001001;
reg    ap_block_pp0_stage7_flag00001001;
reg    ap_block_pp0_stage0_flag00001001;
reg    ap_block_pp0_stage1_flag00001001;
reg    ap_block_pp0_stage2_flag00001001;
reg    ap_block_pp0_stage3_flag00001001;
reg    ap_block_pp0_stage4_flag00001001;
reg    ap_reg_ioackin_output_img_AWREADY;
reg    ap_reg_ioackin_output_img_WREADY;
wire   [0:0] tmp_fu_150_p2;
wire   [0:0] tmp_1_fu_156_p2;
wire   [5:0] i_s_fu_194_p2;
wire   [5:0] grp_fu_223_p0;
wire   [6:0] grp_fu_223_p1;
wire   [0:0] tmp1_mid1_fu_229_p2;
wire   [0:0] tmp_4_fu_239_p2;
wire   [0:0] tmp_5_fu_244_p2;
wire   [0:0] tmp2_fu_249_p2;
wire   [0:0] tmp1_mid2_fu_233_p3;
wire   [6:0] j_cast_fu_264_p1;
wire   [6:0] tmp3_fu_267_p2;
wire  signed [11:0] tmp3_cast_fu_273_p1;
wire   [11:0] tmp_2_fu_282_p2;
wire   [11:0] j_cast6_fu_261_p1;
wire   [6:0] tmp5_fu_303_p2;
wire   [11:0] tmp5_cast_fu_309_p1;
wire   [11:0] tmp_11_0_2_fu_333_p2;
wire   [11:0] tmp_11_1_fu_348_p2;
wire   [11:0] tmp_11_1_2_fu_366_p2;
wire   [11:0] tmp_11_2_fu_387_p2;
wire   [11:0] tmp_11_2_2_fu_412_p2;
wire   [8:0] tmp_13_0_2_cast_fu_431_p1;
wire   [8:0] tmp_131_cast_fu_427_p1;
wire   [8:0] tmp_16_0_1_fu_446_p3;
wire   [8:0] p_shl1_fu_461_p3;
wire  signed [10:0] x_dir_2_0_2_cast_fu_458_p1;
wire   [10:0] p_shl1_cast_fu_468_p1;
wire   [8:0] tmp_15_1_2_fu_478_p3;
wire   [10:0] x_dir_2_1_1_fu_472_p2;
wire   [10:0] tmp_15_1_2_cast_fu_485_p1;
wire   [9:0] tmp4_cast_fu_495_p1;
wire   [9:0] tmp_16_0_1_cast_fu_454_p1;
wire   [9:0] y_dir_2_1_2_fu_498_p2;
wire   [10:0] x_dir_2_1_2_fu_489_p2;
wire   [10:0] tmp_13_2_cast_fu_508_p1;
wire   [10:0] y_dir_2_1_2_cast_fu_504_p1;
wire   [8:0] p_shl_fu_527_p3;
wire   [10:0] p_shl_cast_fu_535_p1;
wire   [10:0] tmp_13_2_2_cast_fu_544_p1;
wire   [10:0] y_dir_2_2_1_fu_539_p2;
wire   [10:0] x_dir_2_2_2_fu_548_p2;
wire   [10:0] y_dir_2_2_2_fu_553_p2;
wire   [7:0] tmp_10_fu_580_p2;
wire   [7:0] tmp_13_fu_591_p2;
wire   [7:0] tmp_11_fu_585_p3;
wire   [7:0] tmp_14_fu_596_p3;
reg    grp_fu_223_ce;
wire    ap_CS_fsm_state30;
reg   [9:0] ap_NS_fsm;
reg    ap_block_pp0_stage1_flag00011011;
reg    ap_block_pp0_stage2_flag00011011;
reg    ap_block_pp0_stage4_flag00011011;
reg    ap_block_pp0_stage5_flag00011011;
reg    ap_block_pp0_stage6_flag00011011;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [11:0] grp_fu_223_p00;
reg    ap_condition_1264;
reg    ap_condition_1268;
reg    ap_condition_777;
reg    ap_condition_791;
reg    ap_condition_803;
reg    ap_condition_815;
reg    ap_condition_826;
reg    ap_condition_838;
reg    ap_condition_851;
reg    ap_condition_863;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_reg_ioackin_input_img_ARREADY = 1'b0;
#0 ap_reg_ioackin_output_img_AWREADY = 1'b0;
#0 ap_reg_ioackin_output_img_WREADY = 1'b0;
end

ip_sobel_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
ip_sobel_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

ip_sobel_input_img_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_INPUT_IMG_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_INPUT_IMG_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_INPUT_IMG_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_INPUT_IMG_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_INPUT_IMG_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_INPUT_IMG_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_INPUT_IMG_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_INPUT_IMG_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_INPUT_IMG_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_INPUT_IMG_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_INPUT_IMG_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_INPUT_IMG_CACHE_VALUE ))
ip_sobel_input_img_m_axi_U(
    .AWVALID(m_axi_input_img_AWVALID),
    .AWREADY(m_axi_input_img_AWREADY),
    .AWADDR(m_axi_input_img_AWADDR),
    .AWID(m_axi_input_img_AWID),
    .AWLEN(m_axi_input_img_AWLEN),
    .AWSIZE(m_axi_input_img_AWSIZE),
    .AWBURST(m_axi_input_img_AWBURST),
    .AWLOCK(m_axi_input_img_AWLOCK),
    .AWCACHE(m_axi_input_img_AWCACHE),
    .AWPROT(m_axi_input_img_AWPROT),
    .AWQOS(m_axi_input_img_AWQOS),
    .AWREGION(m_axi_input_img_AWREGION),
    .AWUSER(m_axi_input_img_AWUSER),
    .WVALID(m_axi_input_img_WVALID),
    .WREADY(m_axi_input_img_WREADY),
    .WDATA(m_axi_input_img_WDATA),
    .WSTRB(m_axi_input_img_WSTRB),
    .WLAST(m_axi_input_img_WLAST),
    .WID(m_axi_input_img_WID),
    .WUSER(m_axi_input_img_WUSER),
    .ARVALID(m_axi_input_img_ARVALID),
    .ARREADY(m_axi_input_img_ARREADY),
    .ARADDR(m_axi_input_img_ARADDR),
    .ARID(m_axi_input_img_ARID),
    .ARLEN(m_axi_input_img_ARLEN),
    .ARSIZE(m_axi_input_img_ARSIZE),
    .ARBURST(m_axi_input_img_ARBURST),
    .ARLOCK(m_axi_input_img_ARLOCK),
    .ARCACHE(m_axi_input_img_ARCACHE),
    .ARPROT(m_axi_input_img_ARPROT),
    .ARQOS(m_axi_input_img_ARQOS),
    .ARREGION(m_axi_input_img_ARREGION),
    .ARUSER(m_axi_input_img_ARUSER),
    .RVALID(m_axi_input_img_RVALID),
    .RREADY(m_axi_input_img_RREADY),
    .RDATA(m_axi_input_img_RDATA),
    .RLAST(m_axi_input_img_RLAST),
    .RID(m_axi_input_img_RID),
    .RUSER(m_axi_input_img_RUSER),
    .RRESP(m_axi_input_img_RRESP),
    .BVALID(m_axi_input_img_BVALID),
    .BREADY(m_axi_input_img_BREADY),
    .BRESP(m_axi_input_img_BRESP),
    .BID(m_axi_input_img_BID),
    .BUSER(m_axi_input_img_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(input_img_ARVALID),
    .I_ARREADY(input_img_ARREADY),
    .I_ARADDR(input_img_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(input_img_RVALID),
    .I_RREADY(input_img_RREADY),
    .I_RDATA(input_img_RDATA),
    .I_RID(input_img_RID),
    .I_RUSER(input_img_RUSER),
    .I_RRESP(input_img_RRESP),
    .I_RLAST(input_img_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(input_img_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(input_img_WREADY),
    .I_WDATA(8'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd0),
    .I_BVALID(input_img_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(input_img_BRESP),
    .I_BID(input_img_BID),
    .I_BUSER(input_img_BUSER)
);

ip_sobel_output_img_m_axi #(
    .USER_DW( 8 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUTPUT_IMG_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUTPUT_IMG_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUTPUT_IMG_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUTPUT_IMG_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUTPUT_IMG_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUTPUT_IMG_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUTPUT_IMG_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUTPUT_IMG_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_OUTPUT_IMG_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_OUTPUT_IMG_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUTPUT_IMG_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUTPUT_IMG_CACHE_VALUE ))
ip_sobel_output_img_m_axi_U(
    .AWVALID(m_axi_output_img_AWVALID),
    .AWREADY(m_axi_output_img_AWREADY),
    .AWADDR(m_axi_output_img_AWADDR),
    .AWID(m_axi_output_img_AWID),
    .AWLEN(m_axi_output_img_AWLEN),
    .AWSIZE(m_axi_output_img_AWSIZE),
    .AWBURST(m_axi_output_img_AWBURST),
    .AWLOCK(m_axi_output_img_AWLOCK),
    .AWCACHE(m_axi_output_img_AWCACHE),
    .AWPROT(m_axi_output_img_AWPROT),
    .AWQOS(m_axi_output_img_AWQOS),
    .AWREGION(m_axi_output_img_AWREGION),
    .AWUSER(m_axi_output_img_AWUSER),
    .WVALID(m_axi_output_img_WVALID),
    .WREADY(m_axi_output_img_WREADY),
    .WDATA(m_axi_output_img_WDATA),
    .WSTRB(m_axi_output_img_WSTRB),
    .WLAST(m_axi_output_img_WLAST),
    .WID(m_axi_output_img_WID),
    .WUSER(m_axi_output_img_WUSER),
    .ARVALID(m_axi_output_img_ARVALID),
    .ARREADY(m_axi_output_img_ARREADY),
    .ARADDR(m_axi_output_img_ARADDR),
    .ARID(m_axi_output_img_ARID),
    .ARLEN(m_axi_output_img_ARLEN),
    .ARSIZE(m_axi_output_img_ARSIZE),
    .ARBURST(m_axi_output_img_ARBURST),
    .ARLOCK(m_axi_output_img_ARLOCK),
    .ARCACHE(m_axi_output_img_ARCACHE),
    .ARPROT(m_axi_output_img_ARPROT),
    .ARQOS(m_axi_output_img_ARQOS),
    .ARREGION(m_axi_output_img_ARREGION),
    .ARUSER(m_axi_output_img_ARUSER),
    .RVALID(m_axi_output_img_RVALID),
    .RREADY(m_axi_output_img_RREADY),
    .RDATA(m_axi_output_img_RDATA),
    .RLAST(m_axi_output_img_RLAST),
    .RID(m_axi_output_img_RID),
    .RUSER(m_axi_output_img_RUSER),
    .RRESP(m_axi_output_img_RRESP),
    .BVALID(m_axi_output_img_BVALID),
    .BREADY(m_axi_output_img_BREADY),
    .BRESP(m_axi_output_img_BRESP),
    .BID(m_axi_output_img_BID),
    .BUSER(m_axi_output_img_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(output_img_ARREADY),
    .I_ARADDR(32'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(output_img_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(output_img_RDATA),
    .I_RID(output_img_RID),
    .I_RUSER(output_img_RUSER),
    .I_RRESP(output_img_RRESP),
    .I_RLAST(output_img_RLAST),
    .I_AWVALID(output_img_AWVALID),
    .I_AWREADY(output_img_AWREADY),
    .I_AWADDR(ap_reg_pp0_iter2_output_img_addr_reg_723),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(output_img_WVALID),
    .I_WREADY(output_img_WREADY),
    .I_WDATA(tmp_6_reg_813),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(1'd1),
    .I_BVALID(output_img_BVALID),
    .I_BREADY(output_img_BREADY),
    .I_BRESP(output_img_BRESP),
    .I_BID(output_img_BID),
    .I_BUSER(output_img_BUSER)
);

ip_sobel_mul_6ns_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 12 ))
ip_sobel_mul_6ns_bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_223_p0),
    .din1(grp_fu_223_p1),
    .ce(grp_fu_223_ce),
    .dout(grp_fu_223_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00011011 == 1'b0))) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00011011 == 1'b0))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00011011 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00011011 == 1'b0)))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_input_img_ARREADY <= 1'b0;
    end else begin
        if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage4_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_predicate_op77_readreq_state7) & (ap_block_pp0_stage5_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_predicate_op81_readreq_state8) & (ap_block_pp0_stage6_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b1 == ap_predicate_op87_readreq_state9) & (ap_block_pp0_stage7_flag00011001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00011001 == 1'b0)))) begin
            ap_reg_ioackin_input_img_ARREADY <= 1'b0;
        end else if ((((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_predicate_op77_readreq_state7) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage5_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_predicate_op81_readreq_state8) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage6_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b1 == ap_predicate_op87_readreq_state9) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage7_flag00001001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage0_flag00001001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage1_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage2_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage3_flag00001001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == input_img_ARREADY) & (ap_block_pp0_stage4_flag00001001 == 1'b0)))) begin
            ap_reg_ioackin_input_img_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_output_img_AWREADY <= 1'b0;
    end else begin
        if ((ap_condition_1264 == 1'b1)) begin
            if ((ap_block_pp0_stage5_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_output_img_AWREADY <= 1'b0;
            end else if (((ap_block_pp0_stage5_flag00001001 == 1'b0) & (1'b1 == output_img_AWREADY))) begin
                ap_reg_ioackin_output_img_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_output_img_WREADY <= 1'b0;
    end else begin
        if ((ap_condition_1268 == 1'b1)) begin
            if ((ap_block_pp0_stage6_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_output_img_WREADY <= 1'b0;
            end else if (((ap_block_pp0_stage6_flag00001001 == 1'b0) & (1'b1 == output_img_WREADY))) begin
                ap_reg_ioackin_output_img_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        i_reg_120 <= tmp_2_mid2_v_v_reg_646;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_120 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        indvar_flatten_reg_109 <= indvar_flatten_next_reg_617;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_reg_109 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        j_reg_131 <= j_1_reg_694;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_reg_131 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage4_flag00011001 == 1'b0))) begin
        abscond7_reg_808 <= abscond7_fu_574_p2;
        abscond_reg_797 <= abscond_fu_564_p2;
        tmp_12_reg_802 <= tmp_12_fu_570_p1;
        tmp_9_reg_791 <= tmp_9_fu_559_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_or_cond5_reg_657 <= or_cond5_reg_657;
        ap_reg_pp0_iter2_or_cond5_reg_657 <= ap_reg_pp0_iter1_or_cond5_reg_657;
        ap_reg_pp0_iter3_or_cond5_reg_657 <= ap_reg_pp0_iter2_or_cond5_reg_657;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter2_output_img_addr_reg_723[11 : 0] <= output_img_addr_reg_723[11 : 0];
        exitcond_flatten_reg_613 <= exitcond_flatten_fu_168_p2;
        tmp1_reg_608 <= tmp1_fu_162_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_168_p2))) begin
        exitcond_reg_622 <= exitcond_fu_180_p2;
        j_mid2_reg_627 <= j_mid2_fu_186_p3;
        tmp_1_mid1_reg_641 <= tmp_1_mid1_fu_206_p2;
        tmp_mid1_reg_636 <= tmp_mid1_fu_200_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        indvar_flatten_next_reg_617 <= indvar_flatten_next_fu_174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6_flag00011001 == 1'b0))) begin
        input_img_addr_2_rea_reg_746 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_predicate_op81_readreq_state8) & (ap_block_pp0_stage6_flag00011001 == 1'b0))) begin
        input_img_addr_2_reg_705[11 : 0] <= tmp_12_0_2_fu_338_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00011001 == 1'b0))) begin
        input_img_addr_3_rea_reg_751 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b1 == ap_predicate_op87_readreq_state9) & (ap_block_pp0_stage7_flag00011001 == 1'b0))) begin
        input_img_addr_3_reg_711[11 : 0] <= tmp_12_1_fu_353_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        input_img_addr_4_rea_reg_756 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        input_img_addr_4_reg_717[11 : 0] <= tmp_12_1_2_fu_371_p1[11 : 0];
        output_img_addr_reg_723[11 : 0] <= tmp_12_1_1_fu_363_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        input_img_addr_5_rea_reg_761 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        input_img_addr_5_reg_728[11 : 0] <= tmp_12_2_fu_392_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00011001 == 1'b0))) begin
        input_img_addr_7_reg_740[11 : 0] <= tmp_12_2_2_fu_417_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_block_pp0_stage4_flag00011001 == 1'b0))) begin
        input_img_addr_reg_674[11 : 0] <= tmp_3_fu_288_p1[11 : 0];
        tmp_10_1_reg_680 <= tmp_10_1_fu_298_p2;
        tmp_10_2_reg_687 <= tmp_10_2_fu_313_p2;
        tmp_s_reg_668 <= tmp_s_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_block_pp0_stage4_flag00011001 == 1'b0))) begin
        j_1_reg_694 <= j_1_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0))) begin
        or_cond5_reg_657 <= or_cond5_fu_255_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage4_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage2_flag00011001 == 1'b0)))) begin
        reg_142 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage5_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage3_flag00011001 == 1'b0)))) begin
        reg_146 <= input_img_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage2_flag00011001 == 1'b0))) begin
        tmp4_reg_771 <= tmp4_fu_440_p2;
        x_dir_2_0_2_reg_766 <= x_dir_2_0_2_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00011001 == 1'b0))) begin
        tmp_2_mid2_reg_661 <= grp_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_168_p2))) begin
        tmp_2_mid2_v_v_reg_646 <= tmp_2_mid2_v_v_fu_212_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage5_flag00011001 == 1'b0))) begin
        tmp_6_reg_813 <= tmp_6_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage3_flag00011001 == 1'b0))) begin
        tmp_8_reg_786 <= tmp_8_fu_523_p1;
        x_dir_2_2_reg_776 <= x_dir_2_2_fu_511_p2;
        y_dir_2_2_reg_781 <= y_dir_2_2_fu_517_p2;
    end
end

always @ (*) begin
    if ((1'd1 == exitcond_flatten_fu_168_p2)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_input_img_ARREADY)) begin
        ap_sig_ioackin_input_img_ARREADY = input_img_ARREADY;
    end else begin
        ap_sig_ioackin_input_img_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_output_img_AWREADY)) begin
        ap_sig_ioackin_output_img_AWREADY = output_img_AWREADY;
    end else begin
        ap_sig_ioackin_output_img_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_output_img_WREADY)) begin
        ap_sig_ioackin_output_img_WREADY = output_img_WREADY;
    end else begin
        ap_sig_ioackin_output_img_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00011001 == 1'b0)))) begin
        grp_fu_223_ce = 1'b1;
    end else begin
        grp_fu_223_ce = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        i_phi_fu_124_p4 = tmp_2_mid2_v_v_reg_646;
    end else begin
        i_phi_fu_124_p4 = i_reg_120;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        indvar_flatten_phi_fu_113_p4 = indvar_flatten_next_reg_617;
    end else begin
        indvar_flatten_phi_fu_113_p4 = indvar_flatten_reg_109;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_input_img_ARREADY)) begin
        if ((ap_condition_863 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_7_reg_740;
        end else if ((ap_condition_851 == 1'b1)) begin
            input_img_ARADDR = tmp_12_2_1_fu_402_p1;
        end else if ((ap_condition_838 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_5_reg_728;
        end else if ((ap_condition_826 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_4_reg_717;
        end else if ((ap_condition_815 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_3_reg_711;
        end else if ((ap_condition_803 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_2_reg_705;
        end else if ((ap_condition_791 == 1'b1)) begin
            input_img_ARADDR = tmp_12_0_1_fu_323_p1;
        end else if ((ap_condition_777 == 1'b1)) begin
            input_img_ARADDR = input_img_addr_reg_674;
        end else begin
            input_img_ARADDR = 'bx;
        end
    end else begin
        input_img_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_predicate_op77_readreq_state7) & (ap_block_pp0_stage5_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_input_img_ARREADY)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_predicate_op81_readreq_state8) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage6_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b1 == ap_predicate_op87_readreq_state9) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage7_flag00001001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage0_flag00001001 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage1_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage2_flag00001001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage3_flag00001001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == ap_reg_ioackin_input_img_ARREADY) & (ap_block_pp0_stage4_flag00001001 == 1'b0)))) begin
        input_img_ARVALID = 1'b1;
    end else begin
        input_img_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage4_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage2_flag00011001 == 1'b0)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage5_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage3_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6_flag00011001 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00011001 == 1'b0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage0_flag00011001 == 1'b0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b1 == ap_enable_reg_pp0_iter2) & (ap_block_pp0_stage1_flag00011001 == 1'b0)))) begin
        input_img_RREADY = 1'b1;
    end else begin
        input_img_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage5_flag00000000 == 1'b0) & (exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage4_flag00000000 == 1'b0) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6_flag00000000 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00000000 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0)) | ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00000000 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00000000 == 1'b0)))) begin
        input_img_blk_n_AR = m_axi_input_img_ARREADY;
    end else begin
        input_img_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage4_flag00000000 == 1'b0) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6_flag00000000 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage7) & (ap_block_pp0_stage7_flag00000000 == 1'b0)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00000000 == 1'b0) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00000000 == 1'b0) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657)))) begin
        input_img_blk_n_R = m_axi_input_img_RVALID;
    end else begin
        input_img_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_613 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00000000 == 1'b0))) begin
        j_phi_fu_135_p4 = j_1_reg_694;
    end else begin
        j_phi_fu_135_p4 = j_reg_131;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage5_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_output_img_AWREADY))) begin
        output_img_AWVALID = 1'b1;
    end else begin
        output_img_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657) & (ap_block_pp0_stage3_flag00011001 == 1'b0))) begin
        output_img_BREADY = 1'b1;
    end else begin
        output_img_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (ap_block_pp0_stage6_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_output_img_WREADY))) begin
        output_img_WVALID = 1'b1;
    end else begin
        output_img_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (ap_block_pp0_stage5_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657))) begin
        output_img_blk_n_AW = m_axi_output_img_AWREADY;
    end else begin
        output_img_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter3) & (1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657))) begin
        output_img_blk_n_B = m_axi_output_img_BVALID;
    end else begin
        output_img_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (ap_block_pp0_stage6_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657))) begin
        output_img_blk_n_W = m_axi_output_img_WREADY;
    end else begin
        output_img_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_block_pp0_stage0_flag00011011 == 1'b0) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_168_p2) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'd1 == exitcond_flatten_fu_168_p2) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((ap_block_pp0_stage1_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((ap_block_pp0_stage2_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if (((ap_block_pp0_stage3_flag00011011 == 1'b0) & ~((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage3_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage3_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((ap_block_pp0_stage4_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((ap_block_pp0_stage5_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((ap_block_pp0_stage6_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((ap_block_pp0_stage7_flag00011011 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abscond7_fu_574_p2 = (($signed(y_dir_2_2_2_fu_553_p2) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign abscond_fu_564_p2 = (($signed(x_dir_2_2_2_fu_548_p2) > $signed(11'd0)) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10_io)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state10_io)) | ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID)));
end

assign ap_block_pp0_stage1_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_flag00001001 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage1_flag00011001 = (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state11_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_flag00011011 = (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state11_io)));
end

assign ap_block_pp0_stage2_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage2_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state12_io)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID)));
end

always @ (*) begin
    ap_block_pp0_stage2_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state12_io)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID)));
end

assign ap_block_pp0_stage3_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_flag00001001 = (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter3) & (1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657) & (1'b0 == output_img_BVALID)));
end

always @ (*) begin
    ap_block_pp0_stage3_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state13_io)) | ((1'b1 == ap_enable_reg_pp0_iter3) & (1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657) & (1'b0 == output_img_BVALID)));
end

always @ (*) begin
    ap_block_pp0_stage3_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_block_state13_io)) | ((1'b1 == ap_enable_reg_pp0_iter3) & (1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657) & (1'b0 == output_img_BVALID)));
end

assign ap_block_pp0_stage4_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage4_flag00011001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | (1'b1 == ap_block_state14_io)));
end

always @ (*) begin
    ap_block_pp0_stage4_flag00011011 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | (1'b1 == ap_block_state14_io)));
end

assign ap_block_pp0_stage5_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage5_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state7_io)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state23_io)));
end

always @ (*) begin
    ap_block_pp0_stage5_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state7_io)) | ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state23_io)));
end

assign ap_block_pp0_stage6_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage6_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state8_io)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state24_io)));
end

always @ (*) begin
    ap_block_pp0_stage6_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state8_io)) | ((1'b1 == ap_enable_reg_pp0_iter2) & (1'b1 == ap_block_state24_io)));
end

assign ap_block_pp0_stage7_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_pp0_stage7_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_pp0_stage7_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_block_state9_io)));
end

always @ (*) begin
    ap_block_state10_io = ((or_cond5_reg_657 == 1'd1) & (1'b0 == ap_sig_ioackin_input_img_ARREADY));
end

assign ap_block_state10_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_io = ((or_cond5_reg_657 == 1'd1) & (1'b0 == ap_sig_ioackin_input_img_ARREADY));
end

assign ap_block_state11_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state12_io = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == ap_sig_ioackin_input_img_ARREADY));
end

assign ap_block_state12_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state13_io = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == ap_sig_ioackin_input_img_ARREADY));
end

assign ap_block_state13_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_io = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == ap_sig_ioackin_input_img_ARREADY));
end

always @ (*) begin
    ap_block_state14_pp0_stage4_iter1 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state15_pp0_stage5_iter1 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state16_pp0_stage6_iter1 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state17_pp0_stage7_iter1 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state18_pp0_stage0_iter2 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state19_pp0_stage1_iter2 = ((1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state20_pp0_stage2_iter2 = ((1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

always @ (*) begin
    ap_block_state21_pp0_stage3_iter2 = ((1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == input_img_RVALID));
end

assign ap_block_state22_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state23_io = ((1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == ap_sig_ioackin_output_img_AWREADY));
end

assign ap_block_state23_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state24_io = ((1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657) & (1'b0 == ap_sig_ioackin_output_img_WREADY));
end

assign ap_block_state24_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state29_pp0_stage3_iter3 = ((1'd1 == ap_reg_pp0_iter3_or_cond5_reg_657) & (1'b0 == output_img_BVALID));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_io = ((1'b0 == ap_sig_ioackin_input_img_ARREADY) & (1'b1 == ap_predicate_op77_readreq_state7));
end

assign ap_block_state7_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((1'b0 == ap_sig_ioackin_input_img_ARREADY) & (1'b1 == ap_predicate_op81_readreq_state8));
end

assign ap_block_state8_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((1'b0 == ap_sig_ioackin_input_img_ARREADY) & (1'b1 == ap_predicate_op87_readreq_state9));
end

assign ap_block_state9_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1264 = ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657));
end

always @ (*) begin
    ap_condition_1268 = ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_enable_reg_pp0_iter2) & (1'd1 == ap_reg_pp0_iter2_or_cond5_reg_657));
end

always @ (*) begin
    ap_condition_777 = ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_predicate_op77_readreq_state7) & (ap_block_pp0_stage5_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_791 = ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_predicate_op81_readreq_state8) & (ap_block_pp0_stage6_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_803 = ((1'b1 == ap_enable_reg_pp0_iter0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b1 == ap_predicate_op87_readreq_state9) & (ap_block_pp0_stage7_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_815 = ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_826 = ((or_cond5_reg_657 == 1'd1) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_block_pp0_stage1_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_838 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_block_pp0_stage2_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_851 = ((1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_block_pp0_stage3_flag00001001 == 1'b0));
end

always @ (*) begin
    ap_condition_863 = ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b1 == ap_enable_reg_pp0_iter1) & (1'd1 == ap_reg_pp0_iter1_or_cond5_reg_657) & (ap_block_pp0_stage4_flag00001001 == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op77_readreq_state7 = ((exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1));
end

always @ (*) begin
    ap_predicate_op81_readreq_state8 = ((exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_readreq_state9 = ((exitcond_flatten_reg_613 == 1'd0) & (or_cond5_reg_657 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign exitcond_flatten_fu_168_p2 = ((indvar_flatten_phi_fu_113_p4 == 12'd2500) ? 1'b1 : 1'b0);

assign exitcond_fu_180_p2 = ((j_phi_fu_135_p4 == 6'd50) ? 1'b1 : 1'b0);

assign grp_fu_223_p0 = grp_fu_223_p00;

assign grp_fu_223_p00 = tmp_2_mid2_v_v_reg_646;

assign grp_fu_223_p1 = 12'd50;

assign i_s_fu_194_p2 = (i_phi_fu_124_p4 + 6'd1);

assign indvar_flatten_next_fu_174_p2 = (indvar_flatten_phi_fu_113_p4 + 12'd1);

assign j_1_fu_318_p2 = (j_mid2_reg_627 + 6'd1);

assign j_cast6_fu_261_p1 = j_mid2_reg_627;

assign j_cast_fu_264_p1 = j_mid2_reg_627;

assign j_mid2_fu_186_p3 = ((exitcond_fu_180_p2[0:0] === 1'b1) ? 6'd0 : j_phi_fu_135_p4);

assign or_cond5_fu_255_p2 = (tmp2_fu_249_p2 & tmp1_mid2_fu_233_p3);

assign p_shl1_cast_fu_468_p1 = p_shl1_fu_461_p3;

assign p_shl1_fu_461_p3 = {{input_img_addr_3_rea_reg_751}, {1'd0}};

assign p_shl_cast_fu_535_p1 = p_shl_fu_527_p3;

assign p_shl_fu_527_p3 = {{reg_142}, {1'd0}};

assign tmp1_fu_162_p2 = (tmp_fu_150_p2 & tmp_1_fu_156_p2);

assign tmp1_mid1_fu_229_p2 = (tmp_mid1_reg_636 & tmp_1_mid1_reg_641);

assign tmp1_mid2_fu_233_p3 = ((exitcond_reg_622[0:0] === 1'b1) ? tmp1_mid1_fu_229_p2 : tmp1_reg_608);

assign tmp2_fu_249_p2 = (tmp_4_fu_239_p2 & tmp_5_fu_244_p2);

assign tmp3_cast_fu_273_p1 = $signed(tmp3_fu_267_p2);

assign tmp3_fu_267_p2 = ($signed(7'd78) + $signed(j_cast_fu_264_p1));

assign tmp4_cast_fu_495_p1 = tmp4_reg_771;

assign tmp4_fu_440_p2 = (tmp_131_cast_fu_427_p1 + tmp_13_0_2_cast_fu_431_p1);

assign tmp5_cast_fu_309_p1 = tmp5_fu_303_p2;

assign tmp5_fu_303_p2 = (7'd50 + j_cast_fu_264_p1);

assign tmp_10_1_fu_298_p2 = (j_cast6_fu_261_p1 + tmp_2_mid2_reg_661);

assign tmp_10_2_fu_313_p2 = (tmp5_cast_fu_309_p1 + tmp_2_mid2_reg_661);

assign tmp_10_fu_580_p2 = (8'd0 - tmp_9_reg_791);

assign tmp_11_0_2_fu_333_p2 = (12'd1 + tmp_s_reg_668);

assign tmp_11_1_2_fu_366_p2 = (12'd1 + tmp_10_1_reg_680);

assign tmp_11_1_fu_348_p2 = ($signed(12'd4095) + $signed(tmp_10_1_reg_680));

assign tmp_11_2_2_fu_412_p2 = (12'd1 + tmp_10_2_reg_687);

assign tmp_11_2_fu_387_p2 = ($signed(12'd4095) + $signed(tmp_10_2_reg_687));

assign tmp_11_fu_585_p3 = ((abscond_reg_797[0:0] === 1'b1) ? tmp_9_reg_791 : tmp_10_fu_580_p2);

assign tmp_12_0_1_fu_323_p1 = tmp_s_reg_668;

assign tmp_12_0_2_fu_338_p1 = tmp_11_0_2_fu_333_p2;

assign tmp_12_1_1_fu_363_p1 = tmp_10_1_reg_680;

assign tmp_12_1_2_fu_371_p1 = tmp_11_1_2_fu_366_p2;

assign tmp_12_1_fu_353_p1 = tmp_11_1_fu_348_p2;

assign tmp_12_2_1_fu_402_p1 = tmp_10_2_reg_687;

assign tmp_12_2_2_fu_417_p1 = tmp_11_2_2_fu_412_p2;

assign tmp_12_2_fu_392_p1 = tmp_11_2_fu_387_p2;

assign tmp_12_fu_570_p1 = y_dir_2_2_2_fu_553_p2[7:0];

assign tmp_131_cast_fu_427_p1 = reg_142;

assign tmp_13_0_2_cast_fu_431_p1 = input_img_addr_2_rea_reg_746;

assign tmp_13_2_2_cast_fu_544_p1 = reg_146;

assign tmp_13_2_cast_fu_508_p1 = input_img_addr_5_rea_reg_761;

assign tmp_13_fu_591_p2 = (8'd0 - tmp_12_reg_802);

assign tmp_14_fu_596_p3 = ((abscond7_reg_808[0:0] === 1'b1) ? tmp_12_reg_802 : tmp_13_fu_591_p2);

assign tmp_15_1_2_cast_fu_485_p1 = tmp_15_1_2_fu_478_p3;

assign tmp_15_1_2_fu_478_p3 = {{input_img_addr_4_rea_reg_756}, {1'd0}};

assign tmp_16_0_1_cast_fu_454_p1 = tmp_16_0_1_fu_446_p3;

assign tmp_16_0_1_fu_446_p3 = {{reg_146}, {1'd0}};

assign tmp_1_fu_156_p2 = ((i_phi_fu_124_p4 < 6'd49) ? 1'b1 : 1'b0);

assign tmp_1_mid1_fu_206_p2 = ((i_s_fu_194_p2 < 6'd49) ? 1'b1 : 1'b0);

assign tmp_2_fu_282_p2 = ($signed(12'd4095) + $signed(tmp_s_fu_277_p2));

assign tmp_2_mid2_v_v_fu_212_p3 = ((exitcond_fu_180_p2[0:0] === 1'b1) ? i_s_fu_194_p2 : i_phi_fu_124_p4);

assign tmp_3_fu_288_p1 = tmp_2_fu_282_p2;

assign tmp_4_fu_239_p2 = ((j_mid2_reg_627 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_5_fu_244_p2 = ((j_mid2_reg_627 < 6'd49) ? 1'b1 : 1'b0);

assign tmp_6_fu_602_p2 = (tmp_11_fu_585_p3 + tmp_14_fu_596_p3);

assign tmp_8_fu_523_p1 = x_dir_2_2_fu_511_p2[7:0];

assign tmp_9_fu_559_p2 = (reg_146 + tmp_8_reg_786);

assign tmp_fu_150_p2 = ((i_phi_fu_124_p4 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_mid1_fu_200_p2 = ((i_s_fu_194_p2 != 6'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_277_p2 = ($signed(tmp3_cast_fu_273_p1) + $signed(tmp_2_mid2_reg_661));

assign x_dir_2_0_2_cast_fu_458_p1 = $signed(x_dir_2_0_2_reg_766);

assign x_dir_2_0_2_fu_434_p2 = (tmp_13_0_2_cast_fu_431_p1 - tmp_131_cast_fu_427_p1);

assign x_dir_2_1_1_fu_472_p2 = ($signed(x_dir_2_0_2_cast_fu_458_p1) - $signed(p_shl1_cast_fu_468_p1));

assign x_dir_2_1_2_fu_489_p2 = (x_dir_2_1_1_fu_472_p2 + tmp_15_1_2_cast_fu_485_p1);

assign x_dir_2_2_2_fu_548_p2 = (x_dir_2_2_reg_776 + tmp_13_2_2_cast_fu_544_p1);

assign x_dir_2_2_fu_511_p2 = (x_dir_2_1_2_fu_489_p2 - tmp_13_2_cast_fu_508_p1);

assign y_dir_2_1_2_cast_fu_504_p1 = y_dir_2_1_2_fu_498_p2;

assign y_dir_2_1_2_fu_498_p2 = (tmp4_cast_fu_495_p1 + tmp_16_0_1_cast_fu_454_p1);

assign y_dir_2_2_1_fu_539_p2 = (y_dir_2_2_reg_781 - p_shl_cast_fu_535_p1);

assign y_dir_2_2_2_fu_553_p2 = (y_dir_2_2_1_fu_539_p2 - tmp_13_2_2_cast_fu_544_p1);

assign y_dir_2_2_fu_517_p2 = (y_dir_2_1_2_cast_fu_504_p1 - tmp_13_2_cast_fu_508_p1);

always @ (posedge ap_clk) begin
    input_img_addr_reg_674[31:12] <= 20'b00000000000000000000;
    input_img_addr_2_reg_705[31:12] <= 20'b00000000000000000000;
    input_img_addr_3_reg_711[31:12] <= 20'b00000000000000000000;
    input_img_addr_4_reg_717[31:12] <= 20'b00000000000000000000;
    output_img_addr_reg_723[31:12] <= 20'b00000000000000000000;
    ap_reg_pp0_iter2_output_img_addr_reg_723[31:12] <= 20'b00000000000000000000;
    input_img_addr_5_reg_728[31:12] <= 20'b00000000000000000000;
    input_img_addr_7_reg_740[31:12] <= 20'b00000000000000000000;
end

endmodule //ip_sobel
