#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" ::: -10
#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 184
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 185
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 212
#pragma line 122 "/usr/include/features.h" 3 4 ::: 309
#pragma line 156 "/usr/include/features.h" 3 4 ::: 334
#pragma line 180 "/usr/include/features.h" 3 4 ::: 336
#pragma line 191 "/usr/include/features.h" 3 4 ::: 339
#pragma line 343 "/usr/include/features.h" 3 4 ::: 370
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 374
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 409
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 416
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 439
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 480
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 486
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 504
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 510
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 514
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 516
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 583
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 624
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 649
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 673
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 674
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 676
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 678
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 679
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 704
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 715
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 720
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 721
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 722
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 728
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 754
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 786
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 787
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 792
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 817
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 819
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 844
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 845
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 864
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 868
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 892
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 896
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 921
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 926
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 943
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 949
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 956
#pragma line 83 "/usr/include/math.h" 3 4 ::: 962
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 963
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1040
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1070
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1311
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1314
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1315
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1318
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1319
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1396
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1426
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1667
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1670
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1671
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1674
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1675
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1752
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1782
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2023
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2026
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2027
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2094
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2096
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2098
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2108
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2110
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2118
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2172
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2174
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2178
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2193
#pragma line 2 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 2249
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2250
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2283
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2324
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2327
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2337
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2366
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2384
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2385
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2441
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2442
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2479
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2481
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2485
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2488
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2506
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 2507
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2535
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2537
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 2539
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 2600
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 2607
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2625
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2630
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 2641
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2710
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2711
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2713
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2715
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2723
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2741
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2744
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2747
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2749
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2750
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2784
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2790
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2806
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2808
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2930
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2944
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2965
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2982
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3010
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3036
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3037
#pragma line 58 "/usr/include/time.h" 3 4 ::: 3058
#pragma line 74 "/usr/include/time.h" 3 4 ::: 3061
#pragma line 90 "/usr/include/time.h" 3 4 ::: 3064
#pragma line 102 "/usr/include/time.h" 3 4 ::: 3067
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3070
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3071
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3072
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3097
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3100
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3110
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3145
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3176
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3199
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3201
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3203
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3204
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3208
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3248
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3259
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3280
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3288
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3290
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3325
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3370
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3400
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3404
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3422
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3433
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3435
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3457
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3461
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3483
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3485
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3487
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3488
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3511
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3533
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3610
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3641
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3642
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3785
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3814
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3839
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3864
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3867
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3876
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3889
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3896
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3908
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3919
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3965
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3974
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3981
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3987
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 4002
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4153
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4155
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4164
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4182
#pragma line 3 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 4185
