#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" ::: 0
#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 194
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 195
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 222
#pragma line 122 "/usr/include/features.h" 3 4 ::: 319
#pragma line 156 "/usr/include/features.h" 3 4 ::: 344
#pragma line 180 "/usr/include/features.h" 3 4 ::: 346
#pragma line 191 "/usr/include/features.h" 3 4 ::: 349
#pragma line 343 "/usr/include/features.h" 3 4 ::: 380
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 384
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 419
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 426
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 449
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 490
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 496
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 514
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 524
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 530
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 540
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 593
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 634
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 659
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 684
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 686
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 688
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 689
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 714
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 725
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 730
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 731
#pragma line 27 "/usr/include/math.h" 2 3 4 ::: 732
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 738
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 764
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 796
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 797
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 802
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 827
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 829
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 854
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 855
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 874
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 878
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 902
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 906
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 931
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 936
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 953
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 959
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 966
#pragma line 83 "/usr/include/math.h" 3 4 ::: 972
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 973
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1050
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1080
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1321
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1324
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1325
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1328
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1329
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1406
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1436
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1677
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1680
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1681
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1684
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1685
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1762
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1792
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2033
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2036
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2037
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2104
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2106
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2108
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2118
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2120
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2128
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2182
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2184
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2188
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2203
#pragma line 2 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 2259
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2260
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2293
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2334
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2337
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2347
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2376
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2394
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2395
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2451
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2452
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2489
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2491
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2495
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2498
#pragma line 27 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2516
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 2517
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2545
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2547
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 2549
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 2610
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 2617
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2635
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 2640
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 2651
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2720
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2721
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2723
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2725
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2733
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2751
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2754
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2757
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2759
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2760
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2794
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2800
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2816
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2818
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2940
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2954
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2975
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2992
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3020
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3046
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3047
#pragma line 58 "/usr/include/time.h" 3 4 ::: 3068
#pragma line 74 "/usr/include/time.h" 3 4 ::: 3071
#pragma line 90 "/usr/include/time.h" 3 4 ::: 3074
#pragma line 102 "/usr/include/time.h" 3 4 ::: 3077
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3080
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3081
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3082
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3107
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3110
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3120
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 3155
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 3186
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3209
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3211
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 3213
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3214
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 3218
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3258
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 3269
#pragma line 118 "/usr/include/time.h" 3 4 ::: 3290
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3298
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 3300
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 3335
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 3380
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3410
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 3414
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3432
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 3443
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3445
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3467
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3471
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3493
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3495
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3497
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3498
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3521
#pragma line 125 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3543
#pragma line 220 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3620
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3651
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3652
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3795
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3824
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3849
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3874
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3877
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3886
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3899
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3906
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3918
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3929
#pragma line 634 "/usr/include/stdlib.h" 3 4 ::: 3975
#pragma line 657 "/usr/include/stdlib.h" 3 4 ::: 3984
#pragma line 712 "/usr/include/stdlib.h" 3 4 ::: 3991
#pragma line 728 "/usr/include/stdlib.h" 3 4 ::: 3997
#pragma line 752 "/usr/include/stdlib.h" 3 4 ::: 4012
#pragma line 911 "/usr/include/stdlib.h" 3 4 ::: 4163
#pragma line 947 "/usr/include/stdlib.h" 3 4 ::: 4165
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 4174
#pragma line 955 "/usr/include/stdlib.h" 2 3 4 ::: 4192
#pragma line 3 "../lab5_custom/lab4_custom.sdk/sobel_filter/src/helloworld.c" 2 ::: 4195
