-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_hls_fptosi_double_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of p_hls_fptosi_double_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv12_C01 : STD_LOGIC_VECTOR (11 downto 0) := "110000000001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_3FF : STD_LOGIC_VECTOR (10 downto 0) := "01111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal p_Result_s_reg_187 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011001 : BOOLEAN;
    signal ap_reg_pp0_iter1_p_Result_s_reg_187 : STD_LOGIC_VECTOR (0 downto 0);
    signal loc_V_1_fu_66_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal loc_V_1_reg_192 : STD_LOGIC_VECTOR (51 downto 0);
    signal isNeg_fu_80_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isNeg_reg_197 : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_assign_1_fu_98_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_assign_1_reg_202 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_2_fu_164_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal p_Val2_2_reg_207 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_flag00000000 : BOOLEAN;
    signal p_Val2_s_fu_44_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal loc_V_fu_56_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_i_i_i_cast1_fu_70_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_assign_fu_74_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_1_i_i_fu_88_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_i_i_cast_fu_94_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_i_i_fu_106_p4 : STD_LOGIC_VECTOR (53 downto 0);
    signal sh_assign_1_cast_fu_119_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_i_i_cast_fu_126_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_i_i_cast_fu_115_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_2_i_i_fu_122_p1 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_3_i_i_fu_130_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_fu_142_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_i_i_fu_136_p2 : STD_LOGIC_VECTOR (136 downto 0);
    signal tmp_5_fu_150_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_6_fu_154_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_6_i_i_fu_171_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_9_i_i_fu_174_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_ce = ap_const_logic_1))) then
                ap_reg_pp0_iter1_p_Result_s_reg_187 <= p_Result_s_reg_187;
                isNeg_reg_197 <= sh_assign_fu_74_p2(11 downto 11);
                loc_V_1_reg_192 <= loc_V_1_fu_66_p1;
                p_Result_s_reg_187 <= p_Val2_s_fu_44_p1(63 downto 63);
                p_Val2_2_reg_207 <= p_Val2_2_fu_164_p3;
                sh_assign_1_reg_202 <= sh_assign_1_fu_98_p3;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_flag00011001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        tmp_9_i_i_fu_174_p2 when (ap_reg_pp0_iter1_p_Result_s_reg_187(0) = '1') else 
        tmp_6_i_i_fu_171_p1;
    isNeg_fu_80_p3 <= sh_assign_fu_74_p2(11 downto 11);
    loc_V_1_fu_66_p1 <= p_Val2_s_fu_44_p1(52 - 1 downto 0);
    loc_V_fu_56_p4 <= p_Val2_s_fu_44_p1(62 downto 52);
    p_Val2_2_fu_164_p3 <= 
        tmp_5_fu_150_p1 when (isNeg_reg_197(0) = '1') else 
        tmp_6_fu_154_p4;
    p_Val2_s_fu_44_p1 <= x;
        sh_assign_1_cast_fu_119_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sh_assign_1_reg_202),32));

    sh_assign_1_fu_98_p3 <= 
        tmp_1_i_i_cast_fu_94_p1 when (isNeg_fu_80_p3(0) = '1') else 
        sh_assign_fu_74_p2;
    sh_assign_fu_74_p2 <= std_logic_vector(signed(ap_const_lv12_C01) + signed(tmp_i_i_i_cast1_fu_70_p1));
        tmp_1_i_i_cast_fu_94_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_i_i_fu_88_p2),12));

    tmp_1_i_i_fu_88_p2 <= std_logic_vector(unsigned(ap_const_lv11_3FF) - unsigned(loc_V_fu_56_p4));
    tmp_2_i_i_cast_fu_126_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_119_p1),54));
    tmp_2_i_i_fu_122_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sh_assign_1_cast_fu_119_p1),137));
    tmp_3_i_i_fu_130_p2 <= std_logic_vector(shift_right(unsigned(tmp_i_i_fu_106_p4),to_integer(unsigned('0' & tmp_2_i_i_cast_fu_126_p1(31-1 downto 0)))));
    tmp_4_i_i_fu_136_p2 <= std_logic_vector(shift_left(unsigned(tmp_i_i_cast_fu_115_p1),to_integer(unsigned('0' & tmp_2_i_i_fu_122_p1(31-1 downto 0)))));
    tmp_5_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_142_p3),31));
    tmp_6_fu_154_p4 <= tmp_4_i_i_fu_136_p2(83 downto 53);
    tmp_6_i_i_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_2_reg_207),32));
    tmp_9_i_i_fu_174_p2 <= std_logic_vector(unsigned(ap_const_lv32_0) - unsigned(tmp_6_i_i_fu_171_p1));
    tmp_fu_142_p3 <= tmp_3_i_i_fu_130_p2(53 downto 53);
    tmp_i_i_cast_fu_115_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_i_i_fu_106_p4),137));
    tmp_i_i_fu_106_p4 <= ((ap_const_lv1_1 & loc_V_1_reg_192) & ap_const_lv1_0);
    tmp_i_i_i_cast1_fu_70_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(loc_V_fu_56_p4),12));
end behav;
