// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ip_sobel_HH_
#define _ip_sobel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "convolution2D.h"
#include "ip_sobel_uitodp_3eOg.h"
#include "ip_sobel_dsqrt_64fYi.h"
#include "ip_sobel_mul_32s_g8j.h"
#include "ip_sobel_horiz_opcud.h"
#include "ip_sobel_vert_opedEe.h"

namespace ap_rtl {

struct ip_sobel : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<20> > input_img_address0;
    sc_out< sc_logic > input_img_ce0;
    sc_in< sc_lv<8> > input_img_q0;
    sc_out< sc_lv<20> > output_img_address0;
    sc_out< sc_logic > output_img_ce0;
    sc_out< sc_logic > output_img_we0;
    sc_out< sc_lv<8> > output_img_d0;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    ip_sobel(sc_module_name name);
    SC_HAS_PROCESS(ip_sobel);

    ~ip_sobel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    ip_sobel_horiz_opcud* horiz_operator_U;
    ip_sobel_vert_opedEe* vert_operator_U;
    convolution2D* grp_convolution2D_fu_119;
    ip_sobel_uitodp_3eOg<1,6,32,64>* ip_sobel_uitodp_3eOg_U6;
    ip_sobel_dsqrt_64fYi<1,31,64,64,64>* ip_sobel_dsqrt_64fYi_U7;
    ip_sobel_mul_32s_g8j<1,3,32,32,32>* ip_sobel_mul_32s_g8j_U8;
    ip_sobel_mul_32s_g8j<1,3,32,32,32>* ip_sobel_mul_32s_g8j_U9;
    sc_signal< sc_lv<49> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > horiz_operator_ce0;
    sc_signal< sc_lv<32> > horiz_operator_q0;
    sc_signal< sc_logic > vert_operator_ce0;
    sc_signal< sc_lv<32> > vert_operator_q0;
    sc_signal< sc_lv<10> > j_1_fu_153_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > exitcond_fu_147_p2;
    sc_signal< sc_lv<32> > grp_convolution2D_fu_119_ap_return;
    sc_signal< sc_lv<32> > tmp1_reg_379;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > grp_convolution2D_fu_119_ap_done;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > grp_fu_159_p2;
    sc_signal< sc_lv<32> > tmp_2_reg_391;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > grp_fu_163_p2;
    sc_signal< sc_lv<32> > tmp_5_reg_396;
    sc_signal< sc_lv<32> > p_fu_169_p2;
    sc_signal< sc_lv<32> > p_reg_401;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > grp_fu_133_p1;
    sc_signal< sc_lv<64> > tmp_6_reg_406;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<64> > grp_fu_136_p2;
    sc_signal< sc_lv<64> > x_assign_reg_411;
    sc_signal< sc_logic > ap_CS_fsm_state46;
    sc_signal< sc_lv<1> > p_Result_s_reg_416;
    sc_signal< sc_logic > ap_CS_fsm_state47;
    sc_signal< sc_lv<52> > loc_V_1_fu_194_p1;
    sc_signal< sc_lv<52> > loc_V_1_reg_421;
    sc_signal< sc_lv<1> > isNeg_fu_208_p3;
    sc_signal< sc_lv<1> > isNeg_reg_426;
    sc_signal< sc_lv<12> > sh_assign_1_fu_226_p3;
    sc_signal< sc_lv<12> > sh_assign_1_reg_431;
    sc_signal< sc_lv<31> > p_Val2_3_fu_292_p3;
    sc_signal< sc_lv<31> > p_Val2_3_reg_436;
    sc_signal< sc_logic > ap_CS_fsm_state48;
    sc_signal< sc_lv<10> > i_1_fu_362_p2;
    sc_signal< sc_logic > ap_CS_fsm_state49;
    sc_signal< sc_logic > grp_convolution2D_fu_119_ap_start;
    sc_signal< sc_logic > grp_convolution2D_fu_119_ap_idle;
    sc_signal< sc_logic > grp_convolution2D_fu_119_ap_ready;
    sc_signal< sc_lv<20> > grp_convolution2D_fu_119_input_img_address0;
    sc_signal< sc_logic > grp_convolution2D_fu_119_input_img_ce0;
    sc_signal< sc_lv<4> > grp_convolution2D_fu_119_operator_address0;
    sc_signal< sc_logic > grp_convolution2D_fu_119_operator_ce0;
    sc_signal< sc_lv<32> > grp_convolution2D_fu_119_operator_q0;
    sc_signal< sc_lv<10> > j_reg_95;
    sc_signal< sc_lv<10> > i_reg_107;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > exitcond1_fu_141_p2;
    sc_signal< sc_logic > ap_reg_grp_convolution2D_fu_119_ap_start;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > tmp_9_fu_344_p1;
    sc_signal< sc_lv<1> > icmp_fu_325_p2;
    sc_signal< sc_lv<64> > tmp_3_fu_357_p1;
    sc_signal< sc_lv<8> > tmp_11_fu_331_p1;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > p_Val2_1_fu_173_p1;
    sc_signal< sc_lv<11> > loc_V_fu_184_p4;
    sc_signal< sc_lv<12> > tmp_i_i_i_i_cast1_fu_198_p1;
    sc_signal< sc_lv<12> > sh_assign_fu_202_p2;
    sc_signal< sc_lv<11> > tmp_13_i_i_i_fu_216_p2;
    sc_signal< sc_lv<12> > tmp_13_i_i_i_cast_fu_222_p1;
    sc_signal< sc_lv<54> > tmp_i_i_i_fu_234_p4;
    sc_signal< sc_lv<32> > sh_assign_1_cast_fu_247_p1;
    sc_signal< sc_lv<54> > tmp_14_i_i_i_cast_fu_254_p1;
    sc_signal< sc_lv<137> > tmp_i_i_i_cast_fu_243_p1;
    sc_signal< sc_lv<137> > tmp_14_i_i_i_fu_250_p1;
    sc_signal< sc_lv<54> > tmp_15_i_i_i_fu_258_p2;
    sc_signal< sc_lv<1> > tmp_fu_270_p3;
    sc_signal< sc_lv<137> > tmp_16_i_i_i_fu_264_p2;
    sc_signal< sc_lv<31> > tmp_4_fu_278_p1;
    sc_signal< sc_lv<31> > tmp_8_fu_282_p4;
    sc_signal< sc_lv<32> > tmp_18_i_i_i_fu_299_p1;
    sc_signal< sc_lv<32> > tmp_21_i_i_i_fu_302_p2;
    sc_signal< sc_lv<32> > p_Val2_s_fu_308_p3;
    sc_signal< sc_lv<24> > tmp_10_fu_315_p4;
    sc_signal< sc_lv<20> > tmp_7_fu_336_p3;
    sc_signal< sc_lv<20> > tmp_s_fu_349_p3;
    sc_signal< sc_logic > grp_fu_159_ce;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > grp_fu_163_ce;
    sc_signal< sc_lv<49> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<49> ap_ST_fsm_state1;
    static const sc_lv<49> ap_ST_fsm_state2;
    static const sc_lv<49> ap_ST_fsm_state3;
    static const sc_lv<49> ap_ST_fsm_state4;
    static const sc_lv<49> ap_ST_fsm_state5;
    static const sc_lv<49> ap_ST_fsm_state6;
    static const sc_lv<49> ap_ST_fsm_state7;
    static const sc_lv<49> ap_ST_fsm_state8;
    static const sc_lv<49> ap_ST_fsm_state9;
    static const sc_lv<49> ap_ST_fsm_state10;
    static const sc_lv<49> ap_ST_fsm_state11;
    static const sc_lv<49> ap_ST_fsm_state12;
    static const sc_lv<49> ap_ST_fsm_state13;
    static const sc_lv<49> ap_ST_fsm_state14;
    static const sc_lv<49> ap_ST_fsm_state15;
    static const sc_lv<49> ap_ST_fsm_state16;
    static const sc_lv<49> ap_ST_fsm_state17;
    static const sc_lv<49> ap_ST_fsm_state18;
    static const sc_lv<49> ap_ST_fsm_state19;
    static const sc_lv<49> ap_ST_fsm_state20;
    static const sc_lv<49> ap_ST_fsm_state21;
    static const sc_lv<49> ap_ST_fsm_state22;
    static const sc_lv<49> ap_ST_fsm_state23;
    static const sc_lv<49> ap_ST_fsm_state24;
    static const sc_lv<49> ap_ST_fsm_state25;
    static const sc_lv<49> ap_ST_fsm_state26;
    static const sc_lv<49> ap_ST_fsm_state27;
    static const sc_lv<49> ap_ST_fsm_state28;
    static const sc_lv<49> ap_ST_fsm_state29;
    static const sc_lv<49> ap_ST_fsm_state30;
    static const sc_lv<49> ap_ST_fsm_state31;
    static const sc_lv<49> ap_ST_fsm_state32;
    static const sc_lv<49> ap_ST_fsm_state33;
    static const sc_lv<49> ap_ST_fsm_state34;
    static const sc_lv<49> ap_ST_fsm_state35;
    static const sc_lv<49> ap_ST_fsm_state36;
    static const sc_lv<49> ap_ST_fsm_state37;
    static const sc_lv<49> ap_ST_fsm_state38;
    static const sc_lv<49> ap_ST_fsm_state39;
    static const sc_lv<49> ap_ST_fsm_state40;
    static const sc_lv<49> ap_ST_fsm_state41;
    static const sc_lv<49> ap_ST_fsm_state42;
    static const sc_lv<49> ap_ST_fsm_state43;
    static const sc_lv<49> ap_ST_fsm_state44;
    static const sc_lv<49> ap_ST_fsm_state45;
    static const sc_lv<49> ap_ST_fsm_state46;
    static const sc_lv<49> ap_ST_fsm_state47;
    static const sc_lv<49> ap_ST_fsm_state48;
    static const sc_lv<49> ap_ST_fsm_state49;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_2D;
    static const sc_lv<32> ap_const_lv32_2E;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<10> ap_const_lv10_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<10> ap_const_lv10_3FF;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_53;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<64> ap_const_lv64_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state46();
    void thread_ap_CS_fsm_state47();
    void thread_ap_CS_fsm_state48();
    void thread_ap_CS_fsm_state49();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_141_p2();
    void thread_exitcond_fu_147_p2();
    void thread_grp_convolution2D_fu_119_ap_start();
    void thread_grp_convolution2D_fu_119_operator_q0();
    void thread_grp_fu_159_ce();
    void thread_grp_fu_163_ce();
    void thread_horiz_operator_ce0();
    void thread_i_1_fu_362_p2();
    void thread_icmp_fu_325_p2();
    void thread_input_img_address0();
    void thread_input_img_ce0();
    void thread_isNeg_fu_208_p3();
    void thread_j_1_fu_153_p2();
    void thread_loc_V_1_fu_194_p1();
    void thread_loc_V_fu_184_p4();
    void thread_output_img_address0();
    void thread_output_img_ce0();
    void thread_output_img_d0();
    void thread_output_img_we0();
    void thread_p_Val2_1_fu_173_p1();
    void thread_p_Val2_3_fu_292_p3();
    void thread_p_Val2_s_fu_308_p3();
    void thread_p_fu_169_p2();
    void thread_sh_assign_1_cast_fu_247_p1();
    void thread_sh_assign_1_fu_226_p3();
    void thread_sh_assign_fu_202_p2();
    void thread_tmp_10_fu_315_p4();
    void thread_tmp_11_fu_331_p1();
    void thread_tmp_13_i_i_i_cast_fu_222_p1();
    void thread_tmp_13_i_i_i_fu_216_p2();
    void thread_tmp_14_i_i_i_cast_fu_254_p1();
    void thread_tmp_14_i_i_i_fu_250_p1();
    void thread_tmp_15_i_i_i_fu_258_p2();
    void thread_tmp_16_i_i_i_fu_264_p2();
    void thread_tmp_18_i_i_i_fu_299_p1();
    void thread_tmp_21_i_i_i_fu_302_p2();
    void thread_tmp_3_fu_357_p1();
    void thread_tmp_4_fu_278_p1();
    void thread_tmp_7_fu_336_p3();
    void thread_tmp_8_fu_282_p4();
    void thread_tmp_9_fu_344_p1();
    void thread_tmp_fu_270_p3();
    void thread_tmp_i_i_i_cast_fu_243_p1();
    void thread_tmp_i_i_i_fu_234_p4();
    void thread_tmp_i_i_i_i_cast1_fu_198_p1();
    void thread_tmp_s_fu_349_p3();
    void thread_vert_operator_ce0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
