# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/project_5/project_5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5 || ORIG_REF_NAME==project_5}]

# IP: bd/project_5/ip/project_5_processing_system7_0_1/project_5_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_processing_system7_0_1 || ORIG_REF_NAME==project_5_processing_system7_0_1}]

# IP: bd/project_5/ip/project_5_ip_sobel_0_0/project_5_ip_sobel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_ip_sobel_0_0 || ORIG_REF_NAME==project_5_ip_sobel_0_0}]

# IP: bd/project_5/ip/project_5_axi_smc_0/project_5_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_axi_smc_0 || ORIG_REF_NAME==project_5_axi_smc_0}]

# IP: bd/project_5/ip/project_5_rst_ps7_0_100M_0/project_5_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_rst_ps7_0_100M_0 || ORIG_REF_NAME==project_5_rst_ps7_0_100M_0}]

# IP: bd/project_5/ip/project_5_ps7_0_axi_periph_1/project_5_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_ps7_0_axi_periph_1 || ORIG_REF_NAME==project_5_ps7_0_axi_periph_1}]

# IP: bd/project_5/ip/project_5_auto_pc_2/project_5_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==project_5_auto_pc_2 || ORIG_REF_NAME==project_5_auto_pc_2}]

# XDC: bd/project_5/project_5_ooc.xdc
